jetstack/tarmak

hack/cherry-pick-pull.sh
=> Adds cherry-pick-pull script from kubernetes

README.md
Helps beginners try out tarmak
```release-note
```
=> Add quickstart section to readme

terraform/Dockerfile
```release-note
upgrade terraform to 0.10.8
```
=> Upgrade terraform to 0.10.8

terraform/amazon/vault/vault_sg.tf
=> Fix name tag for vault SG

.travis.yml
Fetch the full git history (otherwise git subtree will fail)
=> Workaround for travis

terraform/amazon/templates/instance_pools/role_elb.tf.template
```release-note
Raise the master LoadBalancer time out to 3600 seconds
```
=> Raise the timeout for the internal ELB of the API server

.gitlab-ci.yml, .goreleaser.yml, puppet/Rakefile, terraform/amazon/kubernetes/templates/puppet_agent_user_data.yaml, terraform/amazon/tools/templates/bastion_user_data.yaml
```release-note
Sign released binaries using GPG
```
=> Add GPG signing to artifacts

puppet/modules/kubernetes/manifests/kubelet.pp, puppet/modules/kubernetes/manifests/proxy.pp, puppet/modules/kubernetes/templates/kube-proxy.service.erb, puppet/modules/kubernetes/templates/kubelet.service.erb, puppet/modules/tarmak/manifests/worker.pp
Cherry pick of #69 on release-0.2.
#69: Support systemd dependencies for kubelet proxy
=> Automated cherry pick of #69

terraform/amazon/vault/templates/vault_user_data.yaml, terraform/amazon/vault/variables.tf
```release-note
Update vault to 0.9.1
Update consul to 1.0.2
```
fixes #85
=> Update vault to 0.9.1 and consul to 1.0.2

puppet/modules/prometheus/manifests/kube_state_metrics.pp
```release-note
Add alerting rule for restarting Pods
Update kube-state-metrics to v1.2.0
```
=> Enhance kube state metrics

docs/Makefile
=> Ensure multiversion docs build runs on Prow

docs/Makefile
=> Fix permissions for gcloud config folder

docs/index.rst, docs/vault-setup-config.rst
Adds vault setup and config explanation to docs
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #191-gitlab
```release-note
Adds vault setup and config to docs
```
=> Adds vault setup and config to docs

docs/spelling_wordlist.txt, docs/vault-setup-config.rst
```release-note
NONE
```
This should fix the failing doc job
=> Fix vault docs

pkg/tarmak/provider/amazon/security_group.go, pkg/tarmak/role/role.go, pkg/tarmak/stack/rules.go, pkg/terraform/container.go, terraform/amazon/templates/instance_pools/instance_pool.tf.template, terraform/amazon/templates/instance_pools/role_security_group.tf.template, terraform/amazon/tools/bastion.tf
* Generic rules put into rule.go
* Security group terraform generated for stacks
* SG Terraform uploaded to container
Makes rules generic and is generated into terraform when needed
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #63
```release-note
NONE
```
=> Generate security groups

.gitlab-ci.yml, .goreleaser.yml
```release-note
Use upstream goreleaser, GPG signing merged upstream
```
=> Use upstream release of goreleaser 

pkg/tarmak/ssh/tunnel.go
The code before created a long running SSH command that tunneled the
port forward to the localhost. After terminating the SSH command the
tunnel was still kept open by the SSH control master process. The new
behaviour will properly clean up after itself cancel the tunnel.
```release-note
Cleanup SSH tunnels correctly
```
=> Clean up SSH tunnels properly

pkg/tarmak/kubectl/kubectl.go, pkg/tarmak/ssh/tunnel.go
Fixes #129 
```release-note
NONE
```
=> Fix tarmak kubectl tunnel

cmd/tarmak/cmd/root.go
=> Read tarmak's config folder from the environment

docs/design_cli_ux.rst, docs/introduction.rst, docs/spelling_wordlist.txt
There were a few typos I noticed originally but I opted to do a close reading to make sure I had the high-level concepts straight in my head.
These are the changes I opted to make. There are no real edits to content, only changes to the phrasing in some places.
Likely best reviewed in `Split` diff mode on Github.
```release-note
NONE
```
=> Adjust introduction wording

docs/Dockerfile, docs/Makefile
see commits
```release-note
NONE
```
=> Fix docker html container

cmd/tarmak/cmd/cluster_list.go, cmd/tarmak/cmd/root.go, pkg/apis/tarmak/v1alpha1/types.go, pkg/tarmak/config/config.go, pkg/tarmak/config/config_test.go, pkg/tarmak/interfaces/interfaces.go, pkg/tarmak/kubectl/kubectl.go, pkg/tarmak/tarmak.go
```release-note
Allow to override the current cluster set by tarmak.yaml, which is helpful for CI/CD
```
=> Current cluster flags

.gitlab-ci.yml, Makefile, hack/jenkins/Jenkinsfile.tarmak_build
Fixes #176 
```release-note
Provide docker wrapping makefile task
Update to golang 1.9.5
```
=> Add support for building tarmak using Jenkins

pkg/tarmak/cluster/configuration.go, pkg/tarmak/utils/context.go, pkg/terraform/terraform.go
Fixes #183 
```release-note
Return real tarmak cluster plan error code for use in scripts
```
=> Return tarmak cluster plan error code

hack/jenkins/Jenkinsfile.tarmak_build
=> Archive darwin artifact in Jenkins build

docs/index.rst, docs/spelling_wordlist.txt, docs/troubleshooting.rst, docs/troubleshooting/calico.rst
Adds some instruction how to get a calicoctl running with tarmak
```release-note
NONE
```
=> Add some snippet to troubleshoot calicoctl

CHANGELOG.md
=> Update calcio version CHANGELOG.md

puppet/modules/kubernetes/manifests/proxy.pp
Add ipvsadm and conntrack utils to better debug issues with kube-proxy
```release-note
NONE
```
=> Kube-proxy ipvsadm and conntrack

pkg/puppet/puppet.go, puppet/modules/calico/manifests/init.pp, puppet/modules/calico/manifests/node.pp, puppet/modules/kubernetes/manifests/controller_manager.pp, puppet/modules/kubernetes/manifests/init.pp, puppet/modules/kubernetes/templates/kube-controller-manager.service.erb, puppet/modules/kubernetes/templates/kube-proxy.service.erb, puppet/modules/tarmak/manifests/init.pp, puppet/modules/tarmak/manifests/overlay_calico.pp
Respect network CIDRs configured in tarmak.yaml
```release-note
NONE
```
=> Respect network CIDRs configured in tarmak.yaml

terraform/amazon/modules/kubernetes/tags.tf, terraform/amazon/templates/modules.tf.template
Fixes ELB/NLB creation in AWS
```release-note
NONE
```
=> Reenable tagging of subnets

pkg/tarmak/cluster/firewall/rules.go
Fix calico's IPIP protocol rule 
```release-note
NONE
```
=> Fix calico's IPIP protocol rule

CHANGELOG.md, pkg/apis/cluster/v1alpha1/defaults.go, puppet/modules/kubernetes/manifests/params.pp, puppet/modules/tarmak/Makefile, puppet/modules/tarmak/manifests/params.pp, puppet/modules/tarmak/spec/acceptance/single_node_spec.rb
Set new default version to 1.9.7
```release-note
Use kubernetes 1.9.7 as default for new clusters
```
=> Update kubernetes versions

Makefile, cmd/tarmak/cmd/cluster_plan.go
=> Include unstaged files in docker_build

pkg/apis/cluster/v1alpha1/cluster.go, pkg/apis/cluster/v1alpha1/instancepool.go, pkg/tarmak/instance_pool/instance_pool.go, terraform/amazon/templates/instance_pools/instance_pool_iam.tf.template, terraform/amazon/templates/instance_pools/instance_pool_variables.tf.template
Allow specify global and per instance IAM policies
```release-note
Allow users to specify additional global and per instance IAM policies
```
=> Config option to add additional IAM policies

docs/developer-guide.rst
=> Add Puppet development docs

docs/user-guide.rst, docs/user-guide/aws-elasticsearch/elasticsearch.tf
=> Add an AWS Elasticsearch example

.gitignore, Makefile
This extra option makes testing a lot faster on your local machine.
/
```release-note
NONE
```
=> Add local build option to makefile

cmd/tarmak/cmd/cluster_debug_terraform_shell.go, cmd/tarmak/cmd/terraform.go, pkg/terraform/terraform.go
This is further work on @JoshVanL work in #178. 
It had one smaller issue that once we had the shell, the RPC connection to Tarmak was already closed. Due to this we were not able to run terraform plan/apply without errors. By moving the shell creation to another level we fixed this.
fixes #171
Most of the code is based on #178 
```release-note
Re-implement interactive shell for terraform debug shell
```
=>  Re-implements interactive shell for terraform debug shell

cmd/tarmak/cmd/cluster_list.go, pkg/tarmak/cluster/cluster.go, pkg/tarmak/environment/bastion.go, pkg/tarmak/interfaces/interfaces.go, pkg/tarmak/provider/amazon/hosts.go, pkg/tarmak/ssh.go, pkg/tarmak/ssh/ssh.go
Filter `cluster instances list` to display only instances of hub and current cluster.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #195 
PR from my repo to avoid a force push @simonswine 
Rebased onto #205 
```release-note
NONE
```
=> Fix cluster list filter

pkg/tarmak/tarmak.go
Fixes a bug introduced in https://github.com/jetstack/tarmak/pull/247
```release-note-none
NONE
```
=> Update ssh config write to use latest interface

docs/spelling_wordlist.txt, docs/user-guide.rst
Add some small docs on how to add Jenkins to your hub and how to set the SSL cert if needed
```release-note
NONE
```
=> Add Jenkins docs

pkg/tarmak/kubectl/kubectl.go
Fixes #255
```release-note
NONE
```
=> Ensure environment is passed through for kubectl

puppet/modules/kubernetes_addons/manifests/tiller.pp, puppet/modules/kubernetes_addons/spec/classes/tiller_spec.rb, puppet/modules/kubernetes_addons/templates/tiller-deployment.yaml.erb
- Deploy RBAC rules if neccessary
- Ensure tiller listens to localhost only
```release-note
Upgrade default tiller version to 2.9.1
Tiller should listen to localhost only
```
=> Upgrade default tiller version to 2.9.1

docs/spelling_wordlist.txt, docs/user-guide.rst
Reformat and fix order of sections + adding docs for tiller/prometheus
```release-note
NONE
```
=> Tiller prom docs

Gopkg.lock, Gopkg.toml, puppet/modules/vault_client/manifests/params.pp
This is fixes these renewal issues: https://github.com/jetstack/vault-helper/issues/21
```release-note
Update vault-helper with bugfixes for certificate renewal
```
=> Update vault-helper to fix certificate renewal

pkg/tarmak/cluster/cluster.go, pkg/tarmak/environment/environment.go, pkg/tarmak/interfaces/interfaces.go, pkg/tarmak/provider/amazon/amazon.go
Make sure that validate and verify are present on cluster, environment and provider. This streamlines the use of both validate and verify as central calling point instead of all different methods.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)
I need this for #276 
```release-note
NONE
```
=> Refactor validate and verify

.goreleaser.yml, Makefile, hack/minify-binaries.sh
=> Binary compression

docs/user-guide.rst
Add docs for additional IAM polcies
```release-note
NONE
```
=> Add docs for additional IAM policies

puppet/modules/aws_es_proxy/spec/acceptance/nodesets/default.yml, puppet/modules/calico/spec/acceptance/nodesets/default.yml, puppet/modules/etcd/spec/acceptance/nodesets/3n-cluster.yml, puppet/modules/etcd/spec/acceptance/nodesets/default.yml, puppet/modules/fluent_bit/spec/acceptance/nodesets/default.yml, puppet/modules/kubernetes/spec/acceptance/nodesets/default.yml, puppet/modules/tarmak/spec/acceptance/nodesets/default.yml, puppet/modules/vault_client/spec/acceptance/nodesets/default.yml
=> Upgrade centos to the latest version 7.3

docs/spelling_wordlist.txt, docs/user-guide.rst, pkg/apis/cluster/v1alpha1/cluster.go, pkg/apis/cluster/v1alpha1/instancepool.go, pkg/apis/tarmak/v1alpha1/defaults.go, pkg/apis/tarmak/v1alpha1/types.go, pkg/tarmak/cluster/cluster.go, pkg/tarmak/environment/environment.go, pkg/tarmak/instance_pool/instance_pool.go, pkg/tarmak/interfaces/interfaces.go, terraform/amazon/modules/bastion/bastion.tf, terraform/amazon/modules/bastion/inputs.tf, terraform/amazon/modules/jenkins/inputs.tf, terraform/amazon/modules/kubernetes/inputs.tf, terraform/amazon/templates/inputs.tf.template, terraform/amazon/templates/instance_pools/role_security_group.tf.template, terraform/amazon/templates/jenkins_elb.tf.template, terraform/amazon/templates/modules.tf.template
This secures public endpoints (jenkins, bastion, api server) to only allow certain IP ranges.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #198 
**Special notes for your reviewer**: Code is ready, still need to write the docs
```release-note
Secure public endpoints (bastion, jenkins, apiserver) with cidr ranges
```
TODO:
=> Secure endpoints to only allow certain cidr blocks

docs/Dockerfile, docs/Makefile, docs/requirements.txt
```release-note
Ensure sphinx docs build fails if there are errors
```
=> Fix sphinx docs

docs/user-guide.rst
=> Cluster and instance pool section should within IAM additional chapter

docs/user-guide.rst
This will add basic docs for API Server
```release-note
NONE
```
=> Docs for API Server

docs/spelling_wordlist.txt, docs/user-guide.rst, pkg/apis/cluster/v1alpha1/cluster.go, pkg/puppet/puppet.go, pkg/tarmak/cluster/cluster.go, pkg/tarmak/cluster/cluster_test.go, puppet/modules/kubernetes/manifests/apiserver.pp, puppet/modules/kubernetes/manifests/init.pp, puppet/modules/kubernetes/manifests/kubelet.pp, puppet/modules/kubernetes/manifests/scheduler.pp, puppet/modules/kubernetes/templates/kube-apiserver.service.erb, puppet/modules/kubernetes/templates/kube-scheduler.service.erb, puppet/modules/kubernetes/templates/kubelet.service.erb, puppet/modules/kubernetes_addons/manifests/cluster_autoscaler.pp, puppet/modules/kubernetes_addons/spec/classes/cluster_autoscaler_spec.rb, puppet/modules/kubernetes_addons/templates/cluster-autoscaler-deployment.yaml.erb, puppet/modules/kubernetes_addons/templates/cluster-autoscaler-overprovisioning-rbac.yaml.erb, puppet/modules/kubernetes_addons/templates/cluster-autoscaler-overprovisioning.yaml.erb
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #308 https://github.com/jetstack/tarmak/issues/342
```release-note
Support cluster autoscaler overprovisioning
```
=> Support overprovisioning

puppet/modules/kubernetes/manifests/kubelet.pp, puppet/modules/kubernetes/spec/classes/kubelet_spec.rb, puppet/modules/kubernetes/templates/kubelet.service.erb
**What this PR does / why we need it**: This adds full support for hard and soft evictions for the kubelet
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #294 
```release-note
Support hard and soft evictions
```
=> Support hard and soft evictions

puppet/modules/prometheus/manifests/server.pp
```release-note
Enable scraping of controller-manager and scheduler metrics
```
=> Scrape controller-managers and schedulers

docs/spelling_wordlist.txt, docs/user-guide.rst, pkg/puppet/puppet.go, pkg/tarmak/instance_pool/instance_pool.go, puppet/modules/kubernetes_addons/manifests/cluster_autoscaler.pp, puppet/modules/kubernetes_addons/spec/classes/cluster_autoscaler_spec.rb, puppet/modules/kubernetes_addons/templates/cluster-autoscaler-deployment.yaml.erb, terraform/amazon/templates/inputs.tf.template, terraform/amazon/templates/instance_pools/instance_pools.tf.template, terraform/amazon/templates/modules.tf.template
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #324 
```release-note
Support creating and autoscaling an arbitrary number of worker instance pools
```
=> Autoscaling arbitrary worker pools

puppet/modules/tarmak/Makefile
=> Upgrade kubernetes versions for testing

docs/existing-vpc.rst
This just makes the existing VPC docs a little clearer.
```release-note
NONE
```
=> Add note about adding the annotations to all clusters

docs/design_cli_ux.rst
Atm no docs exist for set-context.
```release-note
NONE
```
=> Add docs for set-context

docs/user-guide.rst
**What this PR does / why we need it**: The logging sink documentation needs indenting properly
```release-note
NONE
```
=> Fix logging documentation

pkg/apis/cluster/v1alpha1/instancepool.go
This fixed the struct annotations to omitempty
```release-note
NONE
```
=> Fix typo in struct annotations for Labels

docs/user-guide.rst, pkg/apis/cluster/v1alpha1/defaults.go, pkg/apis/cluster/v1alpha1/instancepool.go, puppet/modules/tarmak/Makefile, puppet/modules/tarmak/manifests/master.pp, puppet/modules/tarmak/spec/acceptance/single_node_spec.rb
Cherry pick of #407 #414 on release-0.4.
#407: Fix logging documentation
#414: Update k8s versions used in tests
```release-note
NONE
```
=> Automated cherry pick of #407 #414

pkg/tarmak/cluster/cluster.go, pkg/tarmak/interfaces/interfaces.go, terraform/amazon/templates/inputs.tf.template, terraform/amazon/templates/instance_pools/instance_pool_variables.tf.template, terraform/amazon/templates/modules.tf.template
Cherry pick of #447 on release-0.4.
#447: Expose root volume sizes as tfvars
=> Automated cherry pick of #447

docs/spelling_wordlist.txt, docs/user-guide.rst, puppet/modules/kubernetes_addons/templates/grafana-deployment.yaml.erb
Cherry pick of #460 on release-0.4.
#460: Change root url for Grafana
=> Automated cherry pick of #460

puppet/Makefile, puppet/modules/aws_ebs/functions/disks.pp, puppet/spec/hosts/etcd_spec.rb, puppet/spec/hosts/master_spec.rb, puppet/spec/hosts/worker_spec.rb
This fixes roles spec, that haven't been run since a while :grimacing: 
/cc @JoshVanL @dippynark 
```release-note
NONE
```
=> Fix role specs

Gopkg.lock, pkg/tarmak/terraform.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #490 
```release-note
Add Terraform debug shell error when binary version is incompatible
```
=> Add Terraform debug shell error when binary version is incompatible

puppet/modules/consul/templates/consul.service.erb, terraform/amazon/modules/vault/templates/vault_user_data.yaml
**What this PR does / why we need it**: If Consul fails we want to restart it
```release-note
Restart Consul on failure
```
=> Restart Consul on failure

CHANGELOG.md, puppet/modules/calico/manifests/node.pp, puppet/modules/calico/manifests/policy_controller.pp, puppet/modules/calico/templates/node-daemonset.yaml.erb
```release-note
Update calico version to 3.1.3
Change tolerations of calico-node to support NoExecute taints in 1.12+
```
=> Upgrade calico to 3.1.3

docs/Makefile
```release-note
NONE
```
/asssign @simonswine @munnerz
=> Adds ci to docs Makefile

docs/user-guide.rst
Add links and fix some typos
```release-note
NONE
```
=> Update Tarmak docs section on PSP

cmd/tarmak/cmd/cluster_images_list.go, pkg/apis/tarmak/v1alpha1/types.go, pkg/packer/packer.go, pkg/tarmak/cluster/cluster.go, pkg/tarmak/interfaces/interfaces.go, pkg/tarmak/provider/amazon/amazon.go, pkg/tarmak/provider/amazon/image.go, pkg/tarmak/tarmak.go, pkg/tarmak/terraform.go
Architecture: Work in progress to enable EBS volume encryption
**Which issue this PR fixes**
fixes #459  
Work in progress
```release-note
Add option to enable EBS encryption
```
=> Select only images that use the correct encrypted setting

puppet/modules/prometheus/manifests/node_exporter.pp
```release-note
Fix node exporter port on etcd nodes
```
/kind bug
=> Fix node-exporter port on etcd nodes

docs/user-guide.rst
Docs on how to use instance storage 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #457 
```release-note
Add docs section about using AWS instance storage
```
=> Add docs about using instance storage

.gitattributes, puppet/.gitattributes
=> Fix github language detection

docs/generated/reference/output/node_modules/highlight.js/lib/highlight.js, docs/generated/reference/output/node_modules/highlight.js/lib/languages/angelscript.js, docs/generated/reference/output/node_modules/highlight.js/lib/languages/cs.js, docs/generated/reference/output/node_modules/highlight.js/lib/languages/reasonml.js, docs/generated/reference/output/node_modules/highlight.js/lib/languages/swift.js, docs/generated/reference/output/node_modules/highlight.js/lib/languages/typescript.js, hack/brodocs/package.json
=> Update and pin highlight.js node_module to 9.13.1

terraform/amazon/templates/modules.tf.template
=> Re-add elb_access_logs_internal_bucket_interval

docs/introduction.rst
```release-note
NONE
```
/assign @simonswine @MattiasGees
=> Fix broken cluster API link

docs/Makefile, docs/introduction.rst
```release-note
Fix documentation broken link and adds Makefile ci target
```
=> Automated cherry pick of #532 #596 origin release 0.4

hack/fluentbit-repo/Dockerfile, hack/fluentbit-repo/Makefile, hack/fluentbit-repo/README.md, puppet/modules/fluent_bit/files/td-agent-bit.repo, puppet/modules/fluent_bit/manifests/daemonset.pp, puppet/modules/fluent_bit/manifests/install.pp, puppet/modules/fluent_bit/manifests/params.pp, puppet/modules/fluent_bit/templates/td-agent-bit.repo.erb
Bump fluentbit to the latest version and brings it in sync with the host fluentbit.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #583 
Tested and logs are shipping without errors.
```release-note
Bump fluentbit to 0.14.6
```
=> Bump fluent bit daemonset to latest version

terraform/amazon/modules/vault/templates/vault_user_data.yaml
```release-note
Adds KMS Server Side Encryption to Consul S3 backups
```
=> Adds KMS SSE to consul backups

cmd/tarmak/cmd/cluster_force-unlock.go
```release-note
NONE
```
/assign @MattiasGees
=> Exit sooner when wrong force-unlock len(args)

CHANGELOG.md, puppet/modules/calico/manifests/node.pp, puppet/modules/calico/manifests/policy_controller.pp
```release-note
Upgrade Calico to 3.1.4
```
=> Upgrade Calico to 3.1.4

puppet/modules/kubernetes_addons/manifests/metrics_server.pp, puppet/modules/kubernetes_addons/manifests/params.pp, puppet/modules/prometheus/Makefile, puppet/modules/prometheus/README.md, puppet/modules/prometheus/manifests/kube_state_metrics.pp, puppet/modules/prometheus/manifests/server.pp
```release-note
Upgrade Prometheus and components to latest version
```
=> Upgrade Prometheus

pkg/terraform/terraform.go
If the puppet module changes in the plan then it will be tainted after. This will cause a mismatch in the plan file and state.
This is run the plan again and save to the plan file so that the legacy puppet module is included.
fixes #628 
```release-note
NONE
```
=> Run plan again if puppet tar gz has been tainted

pkg/tarmak/config/cluster.go, pkg/tarmak/tarmak_test.go, terraform/amazon/templates/inputs.tf.template, terraform/amazon/templates/instance_pools/instance_pool_iam.tf.template, terraform/amazon/templates/instance_pools/instance_pool_instance.tf.template, terraform/amazon/templates/instance_pools/instance_pools.tf.template, terraform/amazon/templates/instance_pools/role_elb.tf.template, terraform/amazon/templates/modules.tf.template, terraform/amazon/templates/outputs.tf.template
Includes Jenkins instance pool into tarmak_test.go
```release-note
NONE
```
=> Adds Jenkins instance pool tests to tarmak_test.go

terraform/amazon/modules/network/outputs.tf, terraform/amazon/modules/state/outputs.tf, terraform/amazon/modules/vault/inputs.tf, terraform/amazon/modules/vault/outputs.tf, terraform/amazon/modules/vault/vault_iam.tf, terraform/amazon/templates/vault_instances.tf.template
fiixes #627 
```release-note
NONE
```
=> Stop hub destroy returning error

puppet/modules/aws_ebs/manifests/mount.pp, puppet/modules/aws_ebs/spec/defines/mount_spec.rb, puppet/modules/aws_ebs/templates/ensure-volume-formatted.service.erb, puppet/modules/tarmak/manifests/etcd.pp, puppet/modules/tarmak/manifests/vault.pp, puppet/modules/tarmak/spec/spec_helper.rb
Correctly mount etcd instances
fixes #449 
```release-note
Correctly mount nvme drives on etcd instances
```
=> Correctly mount nvme drives for etcd instances

packer/amazon/centos-puppet-agent-latest-kernel.json, packer/amazon/centos-puppet-agent.json
Cherry pick of #646 on release-0.5.
#646: Fix centos aws cli again
=> Automated cherry pick of #646

puppet/modules/aws_ebs/manifests/mount.pp, puppet/modules/aws_ebs/spec/defines/mount_spec.rb, puppet/modules/aws_ebs/templates/ensure-volume-formatted.service.erb, puppet/modules/tarmak/manifests/etcd.pp, puppet/modules/tarmak/manifests/vault.pp, puppet/modules/tarmak/spec/spec_helper.rb
Cherry pick of #538 on release-0.5.
#538: Correctly mount nvme drives for etcd instances
=> Automated cherry pick of #538

pkg/tarmak/kubectl/kubectl.go
fixes #647 
```release-note
Override local kubeconfig if errors
```
=> Override entire kubeconfig if errors

pkg/tarmak/kubectl/kubectl.go
Cherry pick of #652 on release-0.5.
#652: Override entire kubeconfig if errors
=> Automated cherry pick of #652

packer/amazon/centos-puppet-agent-latest-kernel.json, packer/amazon/centos-puppet-agent.json, packer/amazon/cleanup.sh, packer/amazon/configure_for_tarmak.sh, packer/amazon/configure_latest_kernel.sh
Cherry pick of #649 on release-0.5.
#649: Migrate packer scripts to separate files
=> Automated cherry pick of #649

docs/OWNERS, puppet/OWNERS, terraform/OWNERS
=> Add owners file

hack/update-reference-docs.sh, packer/amazon/configure_latest_kernel.sh
```release-note
Make sure centos-puppet-agent-latest-kernel is booting into the right kernel
```
=> Fix latest kernel packer image

CHANGELOG.md, Gopkg.toml, puppet/modules/consul/manifests/params.pp, puppet/modules/consul/spec/classes/install_spec.rb, puppet/modules/vault_client/files/vault-dev-server.service, puppet/modules/vault_server/manifests/params.pp, puppet/modules/vault_server/spec/classes/install_spec.rb, terraform/amazon/templates/inputs.tf.template
```release-note
Upgrade Vault to 0.9.6
Upgrade Consul to 1.2.4
```
=> Upgrade vault to 0.9.6 and consul to 1.2.4

.gitlab-ci.yml, Makefile, pkg/packer/image.go, pkg/tarmak/provider/amazon/tf_remote_state.go
```release-note
Upgrade to golang version 1.11.4
```
=> Upgrade to golang version 1.11.4

pkg/tagging_control/tagging_control.go, pkg/tagging_control/tagging_control_test.go, pkg/wing/tags/aws/aws.go
=> Fix signature spelling

pkg/tarmak/ssh/ssh.go
/assign @MattiasGees 
fixes #702
```release-note
NONE
```
=> Ensure cluster directory before creating known_hosts file

Makefile, cmd/tagging_control/cmd/version.go, cmd/tarmak/cmd/version.go, cmd/wing/cmd/version.go, docs/generated/cmd/tagging_control/tagging_control.rst, docs/generated/cmd/tagging_control/tagging_control_version.rst, docs/generated/cmd/wing/wing.rst, docs/generated/cmd/wing/wing_version.rst, hack/lib/version.sh, hack/print-workspace-status.sh, hack/update-cmd-docs.sh, hack/version-ldflags.sh, pkg/version/.gitattributes, pkg/version/base.go, pkg/version/doc.go, pkg/version/version.go, pkg/wing/apiserver/apiserver.go
Generate a nice version number from git/workspace status
```release-note
NONE
```
=> Use kubernetes upstream version scripts

docs/examples/ark.rst, docs/spelling_wordlist.txt
Signed-off-by: Aled James <aledjms@gmail.com>
Adds Heptio Ark example to documentation
fixes #430
```release-note
Add Heptio Ark example to documentation
```
=> Add Heptio Ark example in docs

docs/user-guide.rst
Signed-off-by: Mattias Gees <mattias.gees@gmail.com>
```release-note
NONE
```
=> Extend docs for Pod Security Policy

docs/user-guide.rst
Signed-off-by: Mattias Gees <mattias.gees@gmail.com>
Tiller docs are not correct
```release-note
NONE
```
=> Fix tiller docs

Makefile
=> Use correct path to package

Makefile
=> Remove goreleaser remains

puppet/modules/kubernetes_addons/manifests/metrics_server.pp, puppet/modules/kubernetes_addons/templates/metrics-server-rbac.yaml.erb, puppet/modules/kubernetes_addons/templates/metrics-server.yaml.erb
```release-note
Use custom metrics server image to scrape from Kubelets on master nodes
```
=> Use custom metrics server image for API proxy

pkg/puppet/puppet.go, puppet/modules/etcd/manifests/backup.pp, puppet/modules/etcd/manifests/instance.pp, puppet/modules/tarmak/manifests/etcd.pp, puppet/modules/tarmak/manifests/init.pp, puppet/modules/tarmak/manifests/overlay_calico.pp, puppet/modules/vault_client/manifests/cert_service.pp
=> Remove etcd services when using calico Kubernetes backend 

packer/amazon/configure_for_tarmak.sh
```release-note
Upgrade to Centos 7.6.1810
```
=> Upgrade to Centos 7.6.1810

pkg/tarmak/instance_pool/instance_pool.go, terraform/amazon/modules/bastion/bastion_iam.tf, terraform/amazon/modules/vault/vault_iam.tf
Use role_policy_attachments for additional policies as per https://www.terraform.io/docs/providers/aws/r/iam_policy_attachment.html
```release-note
NONE
```
=> Use role_policy_attachment for additional policies

puppet/modules/fluent_bit/manifests/daemonset.pp, puppet/modules/fluent_bit/manifests/params.pp, puppet/modules/fluent_bit/templates/fluent-bit-daemonset.yaml.erb
```release-note
Upgrade fluentbit to 1.0.4
```
=> Upgrade fluentbit to 1.0.4

terraform/amazon/modules/kubernetes/templates/iam_elb_controller.json
Adds "elasticloadbalancing:AddListenrCertificates" and   "elasticloadbalancing:RemoveListenerCertificates" permissions to ELBs.
fixes #479 
```release-note
Adds AddListenrCertificates and RemoveListenerCertificates permissions to elastic load balancing  
```
=> Adds AddListenrCertificates and RemoveListenerCertificates permissions

terraform/amazon/modules/kubernetes/templates/iam_elb_controller.json
fixes #748 
```release-note
Adds DeregisterTargets permissions to elastic load balancing
```
/cc @BenCoughlan15
=> Adds DeregisterTargets permissionspolicy to elb controller role

puppet/modules/aws_es_proxy/manifests/instance.pp, puppet/modules/aws_es_proxy/templates/aws-es-proxy.service.erb, puppet/modules/fluent_bit/Gemfile.lock, puppet/modules/fluent_bit/manifests/output.pp, puppet/modules/fluent_bit/spec/acceptance/fluentbit_spec.rb, puppet/modules/fluent_bit/spec/defines/output_spec.rb, puppet/modules/fluent_bit/spec/fixtures/elasticsearch.repo
This PR improves the acceptance tests for fluent_bit
Goals:
- Test version is the expected one
- Ensure  aws-es-proxy is setup correctly and working
- Update of configuration with and without AWS proxy
```release-note
NONE
```
=> WIP: Add better acceptance tests for fluentbit

CHANGELOG.md
```release-note
NONE
```
/assign
=> Updates CHANGELOG.md for 0.6.0

Makefile
Cherry pick of #758 on release-0.6.
#758: Revert "Upgrade UPX to 3.95"
=> Automated cherry pick of #758

terraform/amazon/templates/vault_instances.tf.template
```release-note
Use depends_on on the resource rather than the data object
```
=> Change the depends_on to the resource

puppet/hieradata/common.yaml, puppet/modules/consul/files/consul-detect-existing-datacenter.sh, puppet/modules/consul/manifests/install.pp, puppet/modules/consul/manifests/service.pp, puppet/modules/consul/templates/consul.service.erb
```release-note
Set correct datacenter in consul and respect existing datacenters
```
=> Detect existing datacenter

puppet/modules/aws_ebs/manifests/mount.pp, puppet/modules/aws_ebs/spec/defines/mount_spec.rb, puppet/modules/aws_ebs/templates/ensure-volume-formatted.service.erb, puppet/modules/aws_ebs/templates/ensure_volume_formatted.sh.erb, puppet/modules/aws_ebs/templates/volume.mount.erb
```release-note
Support ext4/xfs for new filesystem. Detect fstype of existing ones automatically
```
=> Mount filesystems regardless of type

puppet/hieradata/common.yaml, puppet/modules/aws_ebs/manifests/mount.pp, puppet/modules/aws_ebs/spec/defines/mount_spec.rb, puppet/modules/aws_ebs/templates/ensure-volume-formatted.service.erb, puppet/modules/aws_ebs/templates/ensure_volume_formatted.sh.erb, puppet/modules/aws_ebs/templates/volume.mount.erb, puppet/modules/consul/files/consul-detect-existing-datacenter.sh, puppet/modules/consul/manifests/install.pp, puppet/modules/consul/manifests/service.pp, puppet/modules/consul/templates/consul.service.erb, terraform/amazon/templates/vault_instances.tf.template
Cherry pick of #766 #767 #768 on release-0.6.
#766: Change injection of region
#767: Support ext4 and xfs for formatting empty filesystems
#768: Change the depends_on to the resource
=> Automated cherry pick of #766 #767 #768

Gopkg.lock, Gopkg.toml, vendor/github.com/hashicorp/terraform/terraform/eval_diff.go
Cherry pick of #763 on release-0.6.
#763: Change terraform folder
=> Automated cherry pick of #763

pkg/puppet/puppet.go, pkg/tarmak/config/config.go, pkg/tarmak/environment/environment.go, pkg/tarmak/kubectl/kubectl.go, pkg/tarmak/ssh/ssh.go, pkg/tarmak/utils/files.go, pkg/tarmak/vault/vault.go, pkg/terraform/templating.go, pkg/terraform/terraform.go
```release-note
Replace EnsureDirectoryExists by os.MkdirAll
```
=> Replace EnsureDirectoryExists by os.MkdirAll

pkg/puppet/puppet.go, pkg/tarmak/config/config.go, pkg/tarmak/environment/environment.go, pkg/tarmak/kubectl/kubectl.go, pkg/tarmak/ssh/ssh.go, pkg/tarmak/utils/files.go, pkg/tarmak/vault/vault.go, pkg/terraform/templating.go, pkg/terraform/terraform.go
Cherry pick of #773 on release-0.6.
#773: Replace EnsureDirectoryExists by os.MkdirAll
=> Automated cherry pick of #773

docs/existing-vpc.rst, docs/existing-vpc/vpc.tf
This fixes some issues with the terraform and makes it easy to apply and to include into tarmak.yaml
```release-note
NONE
```
=> Improve usability of existing VPC for testing

pkg/tarmak/ssh/tunnel.go
=> Don't close closed channel in tunnel

pkg/tarmak/ssh/tunnel.go
Cherry pick of #779 on release-0.6.
#779: Don't close closed channel in tunnel
=> Automated cherry pick of #779

packer/amazon/configure_for_tarmak.sh
Signed-off-by: Mattias Gees <mattias.gees@gmail.com>
This disables sctp for https://groups.google.com/forum/?pli=1#!topic/kubernetes-dev/SAiVrpl_kZk
We need to do this in the baseimage as after a disable you need a reboot.
```release-note
Disable SCTP for CVE-2019-3874
```
=> Disable sctp

packer/amazon/configure_for_tarmak.sh
Cherry pick of #784 on release-0.6.
#784: Disable sctp
=> Automated cherry pick of #784

CHANGELOG.md, pkg/apis/cluster/v1alpha1/defaults.go, puppet/modules/tarmak/Makefile
```release-note
Upgrade default Kubernetes version to 1.12.6 
```
=> Upgrade default Kubernetes version to 1.12.6

hack/ci/run-puppet-job.sh
=> Add script for puppet CI jobs 

CHANGELOG.md, Gopkg.lock, Gopkg.toml, puppet/modules/vault_client/files/vault-dev-server.service, puppet/modules/vault_client/manifests/params.pp, vendor/github.com/jetstack/vault-helper/pkg/kubernetes/generic_vault_backend.go, vendor/github.com/jetstack/vault-helper/pkg/kubernetes/init_token.go, vendor/github.com/jetstack/vault-helper/pkg/kubernetes/kubernetes.go, vendor/github.com/jetstack/vault-helper/pkg/kubernetes/pki_vault_backend.go
```release-note
Upgrade vault-helper to 0.9.15
```
=> Updates vault-helper to 0.9.15

puppet/modules/consul/Makefile
=> Adds acceptance-single-node to consul puppet

hack/ci/run-puppet-job.sh
Cherry pick of #790 on release-0.6.
#790: Add script for puppet CI jobs
=> Automated cherry pick of #790

puppet/modules/kubernetes/manifests/apiserver.pp, puppet/modules/kubernetes/spec/classes/apiserver_spec.rb
Cherry pick of #795 on release-0.6.
#795: Remove initializers apiserver admission plugin > 1.14
=> Automated cherry pick of #795

CHANGELOG.md, Gopkg.lock, Gopkg.toml, puppet/modules/vault_client/files/vault-dev-server.service, puppet/modules/vault_client/manifests/params.pp, vendor/github.com/jetstack/vault-helper/pkg/kubernetes/generic_vault_backend.go, vendor/github.com/jetstack/vault-helper/pkg/kubernetes/init_token.go, vendor/github.com/jetstack/vault-helper/pkg/kubernetes/kubernetes.go, vendor/github.com/jetstack/vault-helper/pkg/kubernetes/pki_vault_backend.go
Cherry pick of #803 on release-0.6.
#803: Updates vault-helper to 0.9.15
=> Automated cherry pick of #803

puppet/modules/consul/files/consul-backup.sh, puppet/modules/consul/manifests/init.pp, puppet/modules/consul/manifests/install.pp, puppet/modules/consul/manifests/params.pp, puppet/modules/consul/spec/classes/install_spec.rb
Cherry pick of #799 on release-0.6.
#799: Fixes the installation of consul-backinator
=> Automated cherry pick of #799

.gitlab-ci.yml, Makefile
```release-note
Upgrade golang to 1.11.10
```
=> Upgrade golang to 1.11.10

.gitlab-ci.yml, Makefile
```release-note
Upgrade golang to 1.11.11
```
=> Upgrade golang to 1.11.11

puppet/modules/kubernetes/manifests/apiserver.pp, puppet/modules/kubernetes/manifests/controller_manager.pp, puppet/modules/kubernetes/manifests/kubelet.pp, puppet/modules/kubernetes/manifests/proxy.pp, puppet/modules/kubernetes/manifests/scheduler.pp, puppet/modules/kubernetes/templates/kube-apiserver.service.erb, puppet/modules/kubernetes/templates/kube-controller-manager.service.erb, puppet/modules/kubernetes/templates/kube-proxy.service.erb, puppet/modules/kubernetes/templates/kube-scheduler.service.erb, puppet/modules/kubernetes/templates/kubelet.service.erb, puppet/modules/tarmak/Makefile
```release-note
Support for kubernetes 1.15
```
=> Support for kubernetes 1.15
