jetstack/tarmak

- puppet/modules/kubernetes/manifests/apiserver.pp
- puppet/modules/kubernetes/manifests/kubelet.pp
- puppet/modules/kubernetes/spec/classes/kubelet_spec.rb
- puppet/modules/kubernetes/templates/kube-apiserver.service.erb
- puppet/modules/kubernetes/templates/kubelet.service.erb
- puppet/modules/tarmak/manifests/master.pp
- puppet/modules/tarmak/manifests/worker.pp
This enables verification that everyone that is speaking to the kubelet
is actually authorized and authenticated.
https://kubernetes.io/docs/admin/kubelet-authentication-authorization/
Fixes #44 
This just pulls in the upstream module changes for that
```release-note
Enable authorization and authentication for kubelet
```
> Enable kubelet authorization and authentication

- puppet/modules/kubernetes/manifests/apiserver.pp
- puppet/modules/kubernetes/manifests/init.pp
- puppet/modules/kubernetes/manifests/params.pp
- puppet/modules/kubernetes/spec/acceptance/single_node_spec.rb
- puppet/modules/kubernetes/templates/kube-apiserver.service.erb
- puppet/modules/kubernetes/templates/kubeconfig.erb
- puppet/modules/kubernetes/templates/kubectl-apply.service.erb
- puppet/modules/kubernetes/templates/kubelet.service.erb
- puppet/modules/tarmak/spec/acceptance/single_node_spec.rb
This pulls in the updates to the puppet modules to run the apiserver without an API server insecure port open.
Fixes #43 
```release-note
Disable apiserver binding insecure-port on the master
```
> Disable insecure apiserver port

- pkg/tarmak/terraform.go
Verifies an image exists before running terraform apply. Exits with an error earlier.
**Which issue this PR fixes** 
fixes #19 
```release-note
Verify at least one image exists before running terraform apply
```
> Verify an image exists before running terraform apply

- terraform/amazon/templates/instance_pools/role_security_group.tf.template
This is required for the master to properly access the Pod network using
calico.
```release-note
Allow master to communicate with workers on any port
```
> Allow kubernetes master to access workers on any port

- pkg/tarmak/instance_pool/instance_pool.go
- pkg/tarmak/instance_pool/instance_pool_test.go
- MinCount <= MaxCount
- If the role is stateful then (MinCount == MaxCount), if only one of the two values are set, we should default to the other
- Adds tests -> instance_pool_test.go
- fixes #27
Validates minCount and maxCount of instance pool, adds tests for logic
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # 27
```release-note
Validate minCount and maxCount of Instance Pool
```
> Validate MinCount and MaxCount of Instance Pool

- puppet/modules/kubernetes/manifests/kubelet.pp
- puppet/modules/kubernetes/manifests/proxy.pp
- puppet/modules/kubernetes/templates/kube-proxy.service.erb
- puppet/modules/kubernetes/templates/kubelet.service.erb
- puppet/modules/tarmak/manifests/worker.pp
This make sure that kubelet and kube-proxy are started in the correct order when they are run without puppet
```release-note
Ensure systemd unit order for kubelet and kube-proxy
```
Subtree pull update, so self-lgtming that
> Fix kubelet kube proxy systemd order

- pkg/tarmak/stack/tools_stack.go
* Adds exponential backoff to verify bastion ssh connection
* Quits after 1 min / SIGTERM/INT
* Fixes #56
Tarmak apply sometimes returns error when verifying bastion connection before bastion is finished spinning up
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #56 
```release-note
Retry SSH connection to bastion during tools stack
```
> Retry verify ssh connection to bastion

- pkg/wing/puppet.go
- pkg/wing/wing_test.go
- Sends signals directly for test
- Ensure SIGTERM exits correctly
- Ensure SIGHUP re-converges
fixes #60 
```release-note
`NONE`
```
> Refactor wing tests

- CHANGELOG.md
- pkg/tarmak/provider/amazon/kv.go
- terraform/Dockerfile
- terraform/amazon/kubernetes/iam_policies.tf
- terraform/amazon/kubernetes/providers.tf
- terraform/amazon/kubernetes/puppet_s3.tf
- terraform/amazon/network-existing-vpc/aws.tf
- terraform/amazon/network-existing-vpc/vpc.tf
- terraform/amazon/network/aws.tf
- terraform/amazon/network/outputs.tf
- terraform/amazon/state/aws.tf
- terraform/amazon/state/backup.tf
- terraform/amazon/state/outputs.tf
- terraform/amazon/state/secrets.tf
- terraform/amazon/templates/instance_pools/instance_pool_instance.tf.template
- terraform/amazon/templates/instance_pools/role_elb.tf.template
- terraform/amazon/tools/aws.tf
- terraform/amazon/tools/bastion.tf
- terraform/amazon/vault/aws.tf
- terraform/amazon/vault/tls.tf
- terraform/amazon/vault/tls_s3.tf
- terraform/amazon/vault/variables.tf
- terraform/amazon/vault/vault_dns.tf
- terraform/amazon/vault/vault_iam.tf
- terraform/amazon/vault/vault_instances.tf
- terraform/providers.tf
Terraform 0.11 requires dynamic resource outputs to be lists the required
quite a bit of refactoring.
```release-note
Update terraform to 0.11
```
fixes #84
> Update terraform to 0.11 and update plugins to latest releases

- cmd/tarmak/cmd/root.go
- pkg/apis/tarmak/v1alpha1/types.go
- pkg/docker/app_container.go
- pkg/packer/image.go
- pkg/tarmak/interfaces/interfaces.go
- pkg/tarmak/tarmak.go
- pkg/terraform/container.go
Allows to keep terraform containers around instead of being cleaned up. Help with debugging issues
```release-note
Add `--keep-containers` flag to preserve container environment launched by tarmak
```
> Implement flag to keep terraform containers around

- docs/index.rst
- docs/spelling_wordlist.txt
- docs/vault-helper-guide.rst
- docs/vault-setup-config.rst
Adds vault-helper documentation to Tarmak
== Rebased on top of vault helper/setup docs https://github.com/jetstack/tarmak/pull/51 due to link dependency ==
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #57 
```release-note
`NONE`
```
> vault helper docs

- pkg/tarmak/kubectl/kubectl.go
This fixes issues with machines that can't resolve localhost to
127.0.0.1
```release-note
Use same tunnel address as specified for SSH, fixes tunnels on hosts that can't resolve localhost
```
> Use same local IP as tunnel binds to

- cmd/tarmak/cmd/cluster_apply.go
- cmd/tarmak/cmd/cluster_debug_puppet_build-tar.go
- cmd/tarmak/cmd/cluster_debug_terraform_shell.go
- cmd/tarmak/cmd/cluster_destroy.go
- cmd/tarmak/cmd/cluster_images_build.go
- cmd/tarmak/cmd/cluster_images_list.go
- cmd/tarmak/cmd/cluster_init.go
- cmd/tarmak/cmd/cluster_instances_list.go
- cmd/tarmak/cmd/cluster_instances_ssh.go
- cmd/tarmak/cmd/cluster_kubectl.go
- cmd/tarmak/cmd/cluster_list.go
- cmd/tarmak/cmd/cluster_ssh.go
- cmd/tarmak/cmd/environment_init.go
- cmd/tarmak/cmd/environment_list.go
- cmd/tarmak/cmd/kubectl.go
- cmd/tarmak/cmd/provider_init.go
- cmd/tarmak/cmd/provider_list.go
- cmd/tarmak/cmd/provider_validate.go
- pkg/tarmak/tarmak.go
This cleans up the asset directory in /tmp containing puppet and terraform files 
```release-note
NONE
```
> Clean up tarmak after execution

- puppet/modules/site_module/templates/docker.erb
Fixes #72 
```release-note
Store docker logs in JSON format, with storage size quota
```
> Configure docker to use the json log format

- cmd/tarmak/cmd/cluster_kubectl.go
- cmd/tarmak/cmd/kubectl.go
- cmd/tarmak/cmd/root.go
- cmd/tarmak/main.go
`cluster ssh|kubectl` now escape every flags coming after its mention
and pass the through to the consecutive subcommand. Fixes #5
```release-note
Fix argument parsing for pass through commands `kubectl` and `ssh`
```
> Fix argument parsing for pass through commands

- docs/.dockerignore
- docs/Dockerfile
- docs/Makefile
- docs/developer-guide.rst
Setting up the python environment for the docs is harder than just building the site in docker - which tarmak users will likely have installed.
This is just another option. It's still possible to run create the docs the usual way.
```release-note
It is now possible to build the docs in a container with `make docker_html`
```
> Add task to build docs using docker

- docs/developer-guide.rst
Make symlink command in build instructions kernel independent
```release-note
NONE
```
> Update build instructions

- puppet/modules/kubernetes/templates/kube-apiserver.service.erb
```release-note
Enable endpoint reconciler for kubernetes API server 1.9+
```
> Kube-apiserver should use endpoint reconciler in 1.9+

- puppet/modules/kubernetes/manifests/kubelet.pp
- puppet/modules/kubernetes/spec/classes/kubelet_spec.rb
- puppet/modules/kubernetes/templates/kube-apiserver.service.erb
- puppet/modules/kubernetes/templates/kube-controller-manager.service.erb
- puppet/modules/kubernetes/templates/kube-proxy.service.erb
- puppet/modules/kubernetes/templates/kube-scheduler.service.erb
- puppet/modules/kubernetes/templates/kubelet.service.erb
- puppet/modules/site_module/manifests/docker_config.pp
This ensures we can reserve CPU and memory resources for the system and
the runtime properly in a follow-up PR
```release-note
Setup kubernetes runtime components under cgroup podruntime.slice
```
> Put container runtime resources into a separate slice

- puppet/modules/kubernetes/lib/puppet/functions/five_percent_of_total_ram.rb
- puppet/modules/kubernetes/manifests/kubelet.pp
- puppet/modules/kubernetes/spec/classes/kubelet_spec.rb
- puppet/modules/kubernetes/spec/spec_helper.rb
- puppet/modules/kubernetes/templates/kubelet.service.erb
The kubelet will default to memory.available<100Mi as the hard eviction
threshold. This makes that figure 5% of the total memory or 100Mi.
Whichever is greater.
Read from the default memory facts to set the kubelet `eviction-hard`
parameter.
Default facts:
https://puppet.com/docs/facter/3.10/core_facts.html#memory
Implements https://github.com/jetstack/tarmak/issues/149
```release-note
Sets a kubelet hard eviction target to 5% of the node's total memory.
```
> Set kubelet eviction-hard based on total memory

- pkg/terraform/providers/tarmak/rpc/rpc.go
Otherwise RPC tries to export it and logs an error message.
```release-note
NONE
```
> Make log method private

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/jetstack/vault-helper/pkg/kubernetes/generic.go
- vendor/github.com/jetstack/vault-helper/pkg/kubernetes/init_token.go
- vendor/github.com/jetstack/vault-helper/pkg/kubernetes/kubernetes.go
- vendor/github.com/jetstack/vault-helper/pkg/kubernetes/kubernetes_pki_roles.go
- vendor/github.com/jetstack/vault-helper/pkg/kubernetes/kubernetes_policies.go
- vendor/github.com/jetstack/vault-helper/pkg/kubernetes/pki.go
- vendor/github.com/jetstack/vault-helper/pkg/kubernetes/policy.go
This allows kubelets to get the interal FQDN from *.ec2.internal, which
is used withing us-east-1 of AWS.
```release-note
Fix for clusters in us-east-1 allows kubelets to get the interal FQDN from *.ec2.internal, which
is used only within us-east-1 of AWS
```
> Update vault-helper to 0.9.9

- pkg/tarmak/tarmak.go
When passed a relative config directory e.g. `tarmak -c ./my_dir clusters list` it is not expanded. This meant that an incomplete path was being passed down to terraform runs which now (not running in docker) were failing.
Happy to add try and add a test case for this. Perhaps in `pkg/tarmak/tarmak_test.go`?
```release-note
Always expand relative config path arguments to ensure correct values in generated Terraform config.
```
> Expand relative config directory arguments

- cmd/tarmak/cmd/cluster_list.go
`cluster list` was making cloud provider calls making it slow. This has been removed, in favour of using the local config
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #199 
```release-note
NONE
```
> Show zone info from config when doing `cluster list`

- .gitignore
- puppet/modules/kubernetes/manifests/kubelet.pp
- puppet/modules/kubernetes/spec/classes/kubelet_spec.rb
We've been having an issue using the old label on the latest versions.
Source: https://docs.openshift.com/container-platform/3.6/install_config/persistent_storage/pod_security_context.html
> The volume will be given a type which is accessible by unprivileged containers. This type is usually container_file_t, which treats volumes as container content. Previously, the label specified was svirt_sandbox_file_t. This label is no longer used due to security concerns.
```release-note
Use the container_file_t volume label on newer os versions. …
```
> Toggle SELinux volume label based on OS version

- packer/amazon/centos-puppet-agent-latest-kernel.json
- packer/amazon/centos-puppet-agent.json
- puppet/modules/aws_ebs/manifests/init.pp
- terraform/amazon/modules/vault/templates/vault_user_data.yaml
The package from yum install is currently broken and it means we can't bring up new clusters
The aws-cli we're getting from yum is broken at the moment, installing this version with pip seems to work.
Without it we can't bring up vault etc etc
```release-note
Install awscli in base images using pip to avoid getting broken versions from yum.
```
> Install the aws-cli from pip

- pkg/tarmak/tarmak.go
With the introduction of https://github.com/jetstack/tarmak/pull/194 the default file path didn't work correctly anymore. The filepath was changed to `/~/.tarmak` because of that function. This change fixes that by expanding it before we feed it to the filepath absolute function.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
fixes #203 
I am not really sure we need to keep the changes of #194. Normally the shell expands an relative directory to a full directory before it gives that to the program. IMO this change was introduced because because one type of shell doesn't do it properly.  …
> Fix default file path expansion

- puppet/modules/calico/manifests/node.pp
- puppet/modules/calico/manifests/policy_controller.pp
- puppet/modules/calico/spec/classes/config_spec.rb
- puppet/modules/calico/templates/configmap.yaml.erb
- puppet/modules/calico/templates/node-daemonset.yaml.erb
- puppet/modules/calico/templates/node-rbac.yaml.erb
- puppet/modules/calico/templates/policy-controller-deployment.yaml.erb
Following the guide here:
https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/calico
I made the changes to the calico yaml templates required for 3.1.1
Making sure to continue to mount in the etcd tls files as before.
Updates tarmak's calico deployment to 3.1.1.
We need this so that calico uses etcd 3 as etcd 3 is easier to backup.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
```release-note
Upgrade calico cni plugin to from v2.6 to 3.1.1
```
> Update calico manifests to v3.1.1

- puppet/modules/kubernetes/templates/kube-proxy.service.erb
Enable iptables processing for bridges. Important for non-calico CNI's that use bridges. Otherwise bridge
traffic is not put through iptables
```release-note
Enable iptables processing for bridged traffic
```
> Enable iptables processing for bridges

- packer/amazon/centos-puppet-agent-latest-kernel.json
This continues to use ethX device names on latest upstream kernels
```release-note
NONE
```
> Fix kernel network device names

- pkg/apis/cluster/v1alpha1/defaults.go
Upstream kernel is quite risky and can't be maintained in the long term.
```release-note
NONE
```
> Use centos with rhel kernel as default image

- puppet/modules/tarmak/metadata.json
We were seeing this misleading error on the wing servers:
```
msg="Warning: ModuleLoader: module 'tarmak' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules" app=wing cmd=puppet
```
It's not as serious as it since the node can still converge.
This commit relaxes the minimum version requirement.
```release-note
Relax tarmak puppet module dependencies
```
> Relax tarmak puppet module dependency versions

- .gitignore
Integration tests can leave .kube directories behind - which show in git if not ignored.
```release-note
Ignoore .kube directories from puppet modules
```
> Ignore .kube directories

- puppet/modules/kubernetes/manifests/kubelet.pp
- puppet/modules/kubernetes/spec/classes/kubelet_spec.rb
Before configuring the kubelet directory, fetch the latest selinx policy so that the latest labels are available.
```release-note
Running puppet will now always fetch the latest selinux policy package
```
> Fetch latest selinux package for kubelet config

- terraform/amazon/modules/kubernetes/templates/puppet_agent_user_data.yaml
If the wing fails to start we should restart it because otherwise it's a manual task to ssh in and restart it.
This will attempt a restart if the service fails in anyway - this included the ExecStartPre commands. Restarts will be attempted every 3 seconds.
fixes #230
I've only tested this with a local unit - haven't actually run it in a real cluster.
```release-note
Restart the wing agent service on-failure
```
> Restart the wing agent service on-failure

- puppet/modules/kubernetes/files/audit-policy.yaml
- puppet/modules/kubernetes/manifests/apiserver.pp
- puppet/modules/kubernetes/templates/kube-apiserver.service.erb
**What this PR does / why we need it**: Adds the configuration for api auditing
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #227
Release note:
```release-note
Enable api server advanced audit log for kubernetes version 1.8+
```
> Configure apiserver auditing

- pkg/tarmak/tarmak.go
- pkg/tarmak/terraform.go
Replaces: https://github.com/jetstack/tarmak/pull/189
```release-note
Ensure ssh config for current cluster is present before running terraform commands
```
> Write ssh config at tarmak initialisation to ensure present

- pkg/terraform/templating.go
Currently we don't truncate the files before writing to it. That creates
problems once the file gets shorter than the existing one, as it will
contain extra characters.
```release-note
Ensure templated files are truncated
```
> Ensure templated files are truncated

- pkg/terraform/passthrough.go
- pkg/terraform/terraform.go
Suppress terraform providers stderr when "TF_LOG="
fixes #246 
```release-note
NONE
```
> Suppress provider log output

- cmd/tarmak/cmd/kubectl.go
- pkg/tarmak/interfaces/interfaces.go
- pkg/tarmak/kubectl/kubectl.go
- pkg/terraform/terraform.go
Fixes #184 
```release-note
Allow `tarmak kubectl` to be run from a different location to where the cluster was created
```
> Fix kubectl

- cmd/tarmak/cmd/cluster_plan.go
- pkg/tarmak/terraform.go
- pkg/tarmak/utils/context.go
This signals changes are required, rather than an error occurring.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #193
```release-note
none
```
> Catch exit code 2 from terraform plan

- pkg/tarmak/cluster/wing.go
- pkg/tarmak/environment/bastion.go
- pkg/wing/puppet.go
Use a backoff when connection to wing.
fixes #261
```release-note
NONE
```
> Adds backoff to wing client set

- docs/spelling_wordlist.txt
- docs/user-guide.rst
- puppet/modules/kubernetes/manifests/apiserver.pp
- puppet/modules/kubernetes/templates/kube-apiserver.service.erb
**What this PR does / why we need it**: This PR documents how to configure OIDC in tarmak and making sure the signingArgs parameter is only used when running Kubernetes version 1.10 or above.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #258 
```release-note
Add OIDC documentation
```
> OIDC documentation

- pkg/apis/cluster/v1alpha1/cluster.go
- pkg/puppet/puppet.go
- pkg/puppet/puppet_test.go
- puppet/hieradata/common.yaml
- puppet/hieradata/role/etcd.yaml
- puppet/hieradata/role/master.yaml
- puppet/hieradata/role/worker.yaml
- puppet/modules/prometheus/manifests/init.pp
- puppet/modules/prometheus/manifests/node_exporter.pp
- puppet/modules/prometheus/manifests/server.pp
- puppet/modules/prometheus/templates/prometheus-config-global.yaml.erb
This mode allows a tarmak prometheus deployment, which only contains
scrape_configs for nodes outside of the cluster
```release-note
Implement an external scrape mode for prometheus
```
> Implement an external scrape mode for prometheus

- pkg/tarmak/cluster/init.go
The instance pools of the hub didn't receive the assigned subnets/availability zones from tarmak init. This change fixes.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #162 
```release-note
Add subnets/availability zones to the hub instance pools.
```
> Add subnets/availability zones to the hub instance pools

- terraform/amazon/modules/bastion/bastion.tf
- terraform/amazon/modules/bastion/outputs.tf
- terraform/amazon/modules/jenkins/outputs.tf
- terraform/amazon/modules/network/igw.tf
- terraform/amazon/modules/network/outputs.tf
- terraform/amazon/modules/network/route53.tf
- terraform/amazon/modules/network/routes.tf
- terraform/amazon/modules/network/subnets.tf
- terraform/amazon/modules/network/vpc.tf
- terraform/amazon/modules/network/vpc_endpoints.tf
- terraform/amazon/modules/network/vpc_peering.tf
- terraform/amazon/modules/vault/outputs.tf
- terraform/amazon/modules/vault/tls.tf
- terraform/amazon/modules/vault/tls_s3.tf
- terraform/amazon/modules/vault/vault_dns.tf
- terraform/amazon/modules/vault/vault_instances.tf
- terraform/amazon/modules/vault/vault_sg.tf
- terraform/amazon/templates/instance_pools/role_elb.tf.template
Some outputs were giving errors that it couldn't find an attribute of a resource when running terraform destroy. We had to implement a little hack/workaround to fix this. We add a count of 1 to the resource where the output gave an error. In the output we used the concat and element interpolation functions to fix the ouput. This is based on https://github.com/hashicorp/terraform/issues/16681#issuecomment-345105956 and we see this error since 0.11 (More information on that https://www.terraform.io/upgrade-guides/0-11.html#referencing-attributes-from-resources-with-count-0)
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #257
**Special notes …
> Change resource so that we can run a clean terraform destroy

- pkg/terraform/terraform.go
This fixes a condition where you are not able to destroy because of an unreachable vault_cluster/bastion
```release-note
Run terraform destroy without refreshing data sources
```
> Ensure terraform destroy runs without refreshing data sources

- docs/existing-vpc.rst
**What this PR does / why we need it**: The docs for deploying tarmak into an existing VPC used an incorrect index for accessing the names of the public subnet resource. This PR fixes that
```release-note
NONE
```
> Fix existing VPC docs

- pkg/tarmak/ssh/tunnel.go
- pkg/tarmak/vault/vault.go
This PR fixes the following:
- when testing connection to the bastion before creating vault tunnels, we use the `-N` flag, which shouldn't be used as we are running a remote command (`/bin/true`)
- when creating vault tunnels, if a problem occurs, there was a chance we could hang indefinitely - this change reduces the chance of a blocking channel so that this hanging doesn't occur
```release-note
Improve Vault tunnel creation preventing indefinite hanging in certain situations
```
> Improve vault tunnel creation

- puppet/modules/site_module/manifests/docker_config.pp
**What this PR does / why we need it**: The docker slice drop-in is currently creating a directory instead of a file. The quoting is also rendering the content incorrectly. This change fixes this so that docker actually runs under podruntime.slice.
```release-note
Run docker under podruntime.slice
```
> Fix docker slice drop-in

- terraform/amazon/templates/inputs.tf.template
- terraform/amazon/templates/instance_pools/instance_pool_instance.tf.template
- terraform/amazon/templates/modules.tf.template
**What this PR does / why we need it**: stateful instances are named incorrectly (including the word k8s) and containing hyphens which was inconsistent with the stateless instances. Additionally, jenkins instances had a special prefix  resulting in `tarmak clusters instances list` not working properly. This PR fixes that
```release-note
NONE
```
> Fix stateful instance naming

- pkg/tarmak/config/config.go
- pkg/tarmak/interfaces/interfaces.go
- pkg/tarmak/kubectl/kubectl.go
- pkg/tarmak/tarmak.go
- pkg/tarmak/tarmak_test.go
**What this PR does / why we need it**: This config fixes a number of errors when parsing the config:
- returns descriptive error if failing to parse config
- checks for nil when retrieving using config
- returns descriptive error if current cluster name is in the wrong format
```release-note
Return useful errors when failing to parse config
```
> Fix errors when failing to parse config

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/hashicorp/terraform/helper/schema/resource_diff.go
- vendor/github.com/hashicorp/terraform/terraform/interpolate.go
- vendor/github.com/hashicorp/terraform/version/version.go
**What this PR does / why we need it**: Upgrades vendored terraform to the latest release (0.11.7)
```release-note
Upgrade vendored Terraform to version 0.11.7
```
> Upgrade terraform to 0.11.7

- pkg/puppet/puppet.go
- puppet/hieradata/common.yaml
**What this PR does / why we need it**: Currently the number of instances in an etcd cluster is hard coded to 3. This PR passes through the value from the etcd instance pool to puppet
```release-note
Pass through etcd instance pool min count to puppet
```
> Pass through etcd instance pool min count to puppet

- puppet/modules/fluent_bit/templates/fluent-bit-daemonset.yaml.erb
Without this, setting `hostNetwork: true` will prevent the shipping of
logs to an in-cluster target.
It appears others are configuring fluent-bit in this way:
https://github.com/openstack/openstack-helm-infra/blob/master/fluent-logging/templates/daemonset-fluent-bit.yaml#L98
```release-note
Configure ClusterFirstWithHostNet dnsPolicy for fluent-bit
```
> Use ClusterFirstWithHostNet for fluent-bit daemon set

- terraform/amazon/templates/instance_pools/role_elb.tf.template
When you bring up an Jenkins in your cluster, you will get an AWS/Terraform error to tell you that you try to create 2 ELBs with the same name. This changes solves this by adding the Name of the role to the ELB name. This also fixes the double `-` in the name.
```
DEBU[0136] Error: Error applying plan:  app=tarmak module=terraform std=err
DEBU[0136]                                               app=tarmak module=terraform std=err
DEBU[0136] 1 error occurred:                             app=tarmak module=terraform std=err
DEBU[0136]                                               app=tarmak module=terraform std=err
DEBU[0136] * module.kubernetes.aws_elb.kubernetes_worker: 1 error occurred:  app=tarmak module=terraform std=err
DEBU[0136] …
```
> Fix duplicate ELB name error

- terraform/amazon/templates/inputs.tf.template
- terraform/amazon/templates/modules.tf.template
We can remove this variable both from inputs.tf.template and modules.tf.template because we already template it in from instance_pool_variables.template. In iinstance_pool_variables.template we use GO templating to set the correct instance size. This change fixes that we always brought up Jenkins as an t2.large instead of the size we intended.
Before this change we always installed Jenkins as t2.large
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #311 
```release-note
Fix to set correct instance size for Jenkins.
```
> Remove unneeded input for Jenkins instance size

- puppet/modules/kubernetes_addons/manifests/cluster_autoscaler.pp
- puppet/modules/kubernetes_addons/spec/classes/cluster_autoscaler_spec.rb
**What this PR does / why we need it**: Upgrades CA versions
```release-note
Use latest versions of Cluster Autoscaler
```
> Use latest versions of Cluster Autoscaler

- pkg/tarmak/cluster/firewall/rules.go
**What this PR does / why we need it**: Cluster Autoscaler needs to run on a master for IAM permissions so a security group rule needs to be added to allow Prometheus to scrape metrics
```release-note
NONE
```
> Add security group to allow cluster autoscaler scraping

- puppet/modules/kubernetes/manifests/kubelet.pp
- puppet/modules/kubernetes/spec/acceptance/single_node_spec.rb
- puppet/modules/kubernetes/spec/classes/kubelet_spec.rb
- puppet/modules/site_module/files/20-cgroupfs.conf
- puppet/modules/site_module/manifests/docker.pp
- puppet/modules/site_module/manifests/docker_config.pp
- puppet/modules/tarmak/spec/acceptance/single_node_spec.rb
**What this PR does / why we need it**: When using the systemd driver, node allocatable limits are not being set properly by kubelet. Switching driver to cgroupfs fixes this issue.
```release-note
Change cgroup driver from systemd to cgroupfs for docker and kubelet
```
> Change cgroup driver from systemd to cgroupfs

- terraform/amazon/templates/instance_pools/instance_pool_instance.tf.template
When templating out the terraform config for the etcd stateful instance
pool, this will also create an SRV record in Route53 with a record for
each of the individual A records for each node.
This will eventually allow us to simplify the prometheus scrape config
the 'knowledge' of the number of nodes and their hostnames remains in
terraform only.
dig output:
```
[centos@charlie-cluster|master|ip-10-99-62-26 ~]$ dig etcd-svc.charlie-cluster.tarmak.local. SRV
; <<>> DiG 9.9.4-RedHat-9.9.4-61.el7 <<>> etcd-svc.charlie-cluster.tarmak.local. SRV
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13292
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION: …
```
> Create an SRV record for the etcd instance pool

- cmd/tarmak/cmd/cluster_set-current.go
Currently the only way to  set the current cluster is to edit the yaml. This adds a new cluster subcommand, set-current, that gives the option to change the current-cluster in the CLI.
fixes #155 
```release-note
Add subcommand to set-current cluster
```
> Adds set-current cluster subcommand

- pkg/tarmak/cluster/cluster.go
- pkg/tarmak/cluster/cluster_test.go
- pkg/tarmak/interfaces/interfaces.go
This adds type and count validation checks for cluster instance pools for each cluster type.
fixes #333 #283 #320
This pull request is a consolidation of the fixed issues and the PRs that fixed each individually.
```release-note
NONE
```
> Validate cluster instance pools

- pkg/tarmak/interfaces/interfaces.go
- pkg/terraform/templating.go
- terraform/amazon/templates/inputs.tf.template
Previously, this information was not read in correctly as the bastion and vault 'pools' are different from other instance pools.
I did this while investigating what happens when upgrading to larger vault instances on a live cluster.
Changing the size of nodes for bastion and vault pools in the config file wasn't having any effect.
```release-note
Correctly apply bastion and vault aws instance type from tarmak.yaml
```
> Use bastion and vault instance type from config

- pkg/tarmak/environment/environment.go
- pkg/tarmak/provider/amazon/amazon.go
- pkg/tarmak/vault/vault.go
- pkg/terraform/providers/tarmak/resource_vault_cluster.go
- pkg/terraform/providers/tarmak/resource_vault_instance_role.go
- pkg/terraform/providers/tarmak/rpc/rpc.go
- pkg/terraform/providers/tarmak/rpc/vault_cluster_status.go
- pkg/terraform/providers/tarmak/rpc/vault_instance_role.go
- terraform/amazon/modules/kubernetes/inputs.tf
- terraform/amazon/modules/kubernetes/vault.tf
- terraform/amazon/modules/vault/inputs.tf
- terraform/amazon/modules/vault/vault_instances.tf
- terraform/amazon/templates/inputs.tf.template
- terraform/amazon/templates/modules.tf.template
Use new vault-helper api to use a dry run on ensure. This means nothing is changed if not needed & a terraform plan will return if changes are needed. Also uses delete on terraform destroy. 
A vault-helper ensure will happen with a hub apply.
**Which issue this PR fixes** 
fixes #180
fixes #168 
Uses vault-helper 0.9.12
```release-note
vault-helper initialises PKI during cluster hub apply
```
> vault-helper dry run and delete

- docs/user-guide.rst
- puppet/modules/kubernetes_addons/manifests/tiller.pp
- puppet/modules/kubernetes_addons/templates/tiller-deployment.yaml.erb
**What this PR does / why we need it**: Upgrade the Tiller puppet module and docs
```release-note
Upgrade Tiller manifest versions and documentation
```
> Upgrade Tiller puppet module and docs

- pkg/tarmak/cluster/roles.go
- terraform/amazon/templates/instance_pools/instance_pool_instance.tf.template
**What this PR does / why we need it**: The worker pool is deployed with an unnecessary ELB
Fixes: https://github.com/jetstack/tarmak/issues/334
```release-note
NONE
```
> Remove internal worker ELB

- CHANGELOG.md
- Gopkg.lock
- Gopkg.toml
- pkg/terraform/templating.go
- puppet/modules/vault_client/files/vault-dev-server.service
- puppet/modules/vault_client/manifests/params.pp
- terraform/amazon/modules/vault/vault_instances.tf
- terraform/amazon/templates/vault_instances.tf.template
- vendor/github.com/jetstack/vault-helper/pkg/kubernetes/kubernetes_pki_roles.go
Ensure dry run was panicking due to a logic error in vault-helper. This PR upgrades vault-helper to fix this issue. 
fixes #363 
```release-note
Upgrade vault-helper to 0.9.13
```
> Update vault-helper to 0.9.13

- pkg/tarmak/cluster/cluster.go
We had an issue (https://github.com/jetstack/tarmak/issues/377) where weneeded to plan the hub just to get the local files in place before running operations against other clusters.
This 'Prepares' the hub cluster before verifying it which puts the required files in place.
If the hub has not been applied, then trying to terraform another cluster in the env will still fail.
I've also added a comment explaining this function a little more as it's caused me some confusion in the past.
Fixes https://github.com/jetstack/tarmak/issues/377
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/jetstack/tarmak/issues/377
**Special notes …
> Prepare hub before terraforming other clusters

- pkg/tarmak/environment/environment.go
- pkg/tarmak/initialize/initialize.go
- pkg/tarmak/provider/amazon/amazon.go
- pkg/tarmak/tarmak.go
- pkg/tarmak/terraform.go
- This moves everything that does an external call to the verify method.
- Check if our AWS credentials are correctly setup is the first verify step and it will fail on that if it doesn't work. AWS unfortunately doesn't have a better way of checking our AWS credentials and getting a better error back is really hard.
- Run verify step on provider check and not only the validate step
- Fails a bit better now
```
validation failed: 1 error occurred:
* There was a problem with veryfing your AWS credentials: NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will …
> Improve AWS validate/verify

- pkg/tarmak/environment/environment.go
**What this PR does / why we need it**: Master is currently broken due to a multierror not being returned with `ErrorOrNil`
```release-note
NONE
```
> Return multierror with ErrorOrNil

- terraform/amazon/modules/state/outputs.tf
Terraform destroy failed due to an empty variable due to interpolation. This change makes sure the variable is never empty but has at least one element in it.
Probably needs to be cherry picked for 0.4
```release-note
NONE
```
> Fix failing terraform destroy

- terraform/amazon/modules/state/outputs.tf
Cherry pick of #397 on release-0.4.
```release-note
NONE
```
#397: Fix failing terraform destroy
> Automated cherry pick of #397

- pkg/wing/controller.go
Fixes #385.
```release-note
Recreate wing instances when absent
```
> Recreate wing instances when absent

- Gopkg.lock
- pkg/tarmak/instance_pool/instance_pool.go
- pkg/tarmak/instance_pool/instance_pool_test.go
- Taints and labels can have blank values
- Keys can have slashes and other characters as permitted here:
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set
Fixes https://github.com/jetstack/tarmak/issues/400
I haven't checked that this is templated correctly by the puppet code yet
```release-note
Allow blank values and a wider range of keys for instance pool labels & taints
```
> Relax Label and Taint validations

- puppet/modules/calico/templates/node-daemonset.yaml.erb
- puppet/modules/fluent_bit/templates/fluent-bit-daemonset.yaml.erb
- puppet/modules/prometheus/templates/node-exporter-ds.yaml.erb
Implements additional tolerations for infrastructure pods - see: https://github.com/jetstack/tarmak/issues/404
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:
Fixes https://github.com/jetstack/tarmak/issues/404
Two questions:
- do we need to handle before_1_6 in fluent-bit and the node-exporter?
- should these only tolerate NoSchedule? I set them to tolerate everything.
```release-note
Broaden scope of dedicated tolerations for infrastructure pods.
```
> Tolerate dedicated on calico, node-exporter & fluent-bit

- pkg/apis/cluster/v1alpha1/defaults.go
- pkg/apis/cluster/v1alpha1/defaults_test.go
- pkg/apis/cluster/v1alpha1/logging.go
**What this PR does / why we need it**: Set more sensible defaults for TLS when logging
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #403 
```release-note
Use TLS by default for logging sinks
```
> Use TLS by default for logging sinks

- puppet/modules/kubernetes/manifests/apiserver.pp
- puppet/modules/kubernetes/templates/kube-apiserver.service.erb
**What this PR does / why we need it**: Fixes audit log max backups and log location
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #384
```release-note
Fix apiserver audit log location and rotation
```
> Fix audit max backups and log location

- pkg/apis/cluster/v1alpha1/defaults.go
- pkg/apis/cluster/v1alpha1/defaults_test.go
- pkg/apis/cluster/v1alpha1/logging.go
- pkg/wing/controller.go
- puppet/modules/fluent_bit/templates/fluent-bit-daemonset.yaml.erb
- puppet/modules/kubernetes/manifests/apiserver.pp
- puppet/modules/kubernetes/templates/kube-apiserver.service.erb
Cherry pick of #185 #319 #386 #387 #408 on release-0.4.
#185: Prepare terraform when running kubectl
#319: Use ClusterFirstWithHostNet for fluent-bit ds
#386: Fix audit max backups and log location
#387: Recreate wing instances when absent
#408: Use TLS by default for logging sinks
```release-note
cherry-pick additional fixes to 0.4 release
```
> Automated cherry pick of #185 #319 #386 #387 #408

- docs/spelling_wordlist.txt
- docs/user-guide.rst
- puppet/modules/kubernetes_addons/templates/grafana-deployment.yaml.erb
The place of the proxy got changed in the root url. Kubernetes reports grafana to be available at https://127.0.0.1:54240/api/v1/namespaces/kube-system/services/monitoring-grafana/proxy. This brings the Grafana config to the same level.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #450
I tested this on `1.10.5` and `1.9.10`
```release-note
Fix grafana in cluster service
```
> Change root url for Grafana

- pkg/tarmak/cluster/cluster.go
- pkg/tarmak/interfaces/interfaces.go
- terraform/amazon/templates/inputs.tf.template
- terraform/amazon/templates/instance_pools/instance_pool_variables.tf.template
- terraform/amazon/templates/modules.tf.template
Before, these variables were never exposed and all root volumes got the
default for that variable, 32gb.
```release-note
Set root volume attribute variables, previously only default was used.
```
> Expose root volume sizes as tfvars

- docs/Makefile
This ensures that even if `docker start` fails when trying to build the docs, the output build files are copied out. This helps to get build error messages.
```release-note
NONE
```
> Copy docker files even when start fails

- puppet/hieradata/role/etcd.yaml
- puppet/modules/airworthy/manifests/init.pp
Airworthy puppet module had a class loop which this PR fixes
```release-note
NONE
```
/assign @dippynark @simonswine
> Applies hot fix for class loop in airworthy module

- puppet/hieradata/role/master.yaml
- puppet/modules/kubernetes_addons/manifests/metrics_server.pp
- puppet/modules/kubernetes_addons/spec/classes/metrics_server_spec.rb
- puppet/modules/kubernetes_addons/templates/metrics-server-rbac.yaml.erb
- puppet/modules/kubernetes_addons/templates/metrics-server.yaml.erb
**What this PR does / why we need it**: Adds metrics server as a default add-on from Kubernetes 1.7 onwards
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: related to #427 
```release-note
Add metrics-server add-on from Kubernetes version 1.7 onwards
```
> Add metrics server

- pkg/tarmak/cluster/cluster.go
- pkg/tarmak/cluster/cluster_test.go
It needs to be possible to setup a Jenkins server in the hub.
```release-note
Jenkins is a valid instancepool for hub
```
> Validate Jenkins as a valid instance pool for hub

- terraform/amazon/modules/bastion/templates/bastion_user_data.yaml
Signed-off-by: Luke Addison <luke.addison@jetstack.io>
**What this PR does / why we need it**: Restarts etcd and wing-server when they fail
```release-note
Restart etcd and wing-server on the bastion automatically on failure
```
> Restart bastion etcd and wing-server on failure

- pkg/packer/image.go
- pkg/tarmak/provider/amazon/amazon.go
- pkg/tarmak/provider/amazon/amazon_test.go
- pkg/tarmak/provider/amazon/key_pair.go
- pkg/tarmak/provider/amazon/key_pair_test.go
- pkg/tarmak/provider/amazon/route53.go
- pkg/tarmak/provider/amazon/tf_remote_state.go
- terraform/amazon/templates/inputs.tf.template
- terraform/amazon/templates/modules.tf.template
Generate a KMS key and alias for the provider. This is used to encrypt the terraform remote state.
fixes #467 
```release-note
KMS encrypt terraform remote S3 state data.
```
> KMS encrypt terraform remote state

- docs/proposals/spiffe-spire-integration.rst
- docs/spelling_wordlist.txt
This adds a document detailing the feasibility of adding spire into the Tarmak cluster. It includes steps needed to achieve this and results of some testing.
fixes #436
```release-note
SPIFFE/SPIRE proposal/feasibility document.
```
> Spire proposal/testing results doc

- pkg/tarmak/provider/amazon/tf_remote_state.go
Fixes variable order in RemoteStateName fmt.Sprintf
```release-note
NONE
```
> Adds hot fix to remote state variable order

- terraform/amazon/templates/instance_pools/role_elb.tf.template
We were observing thousands of `TLS handshake error` in the `kube-apiserver` logs coming from ELB ENIs. Updating the ELB's healthcheck fixes it.
```
Sep 14 02:06:54 ip-10-1-31-80.eu-west-2.compute.internal apiserver[18739]: I0914 02:06:54.699402   18739 logs.go:41] http: TLS handshake error from 10.1.20.13:50152: EOF
Sep 14 02:06:57 ip-10-1-31-80.eu-west-2.compute.internal apiserver[18739]: I0914 02:06:57.644306   18739 logs.go:41] http: TLS handshake error from 10.1.10.208:56402: EOF
Sep 14 02:07:14 ip-10-1-31-80.eu-west-2.compute.internal apiserver[18739]: I0914 02:07:14.207835   18739 logs.go:41] http: TLS handshake error from 10.1.21.214:24194: EOF
Sep 14 02:07:14 ip-10-1-31-80.eu-west-2.compute.internal apiserver[18739]: I0914 02:07:14.209522 …
```
> Fix API ELBs SSL healthcheck endpoint

- pkg/tarmak/interfaces/interfaces.go
- pkg/tarmak/provider/amazon/amazon.go
- pkg/tarmak/provider/amazon/key_pair.go
- pkg/tarmak/provider/amazon/key_pair_test.go
- pkg/tarmak/provider/amazon/tf_remote_state.go
- pkg/tarmak/tarmak.go
- pkg/tarmak/terraform.go
Validate / Verify was not being run on a `cluster debug terraform shell` meaning that the remote KMS for the lock was never being retrieved.
```release-note
NONE
```
> Ensure validate/verify is run during a debug shell

- pkg/tarmak/provider/amazon/tf_remote_state.go
When applying the kubernetes part in a multi-cluster, you get errors in the verify step of the verification of the hub.
This is because the variables are not correctly propagated and we ended up with a terraform state configuration of hub that was pointing to the state of the kubernetes part. This small fix fixes that.
This bug was introduced with https://github.com/jetstack/tarmak/commit/37bb501250ab4ae502520efda380cbca10d812dd
```release-note
NONE
```
> Fix verify of multicluster

- pkg/tarmak/environment/bastion.go
- pkg/tarmak/vault/vault.go
Use a healthy vault tunnel to connect to instead of first. Implement getting healthy tunnel, initialization and unseal check using constant interval backoff. 
fixes #507 
Special Notes:
I've added a log Info for when the connection to the bastion host has been successful. Currently it will just warn when it re-tries which can give the impression it never does.
```release-note
Ensure connected vault tunnel is healthy
```
/assign 
/hold
> Use healthy vault tunnel and implement constant backoff

- pkg/tarmak/vault/vault.go
I span up a hub cluster and got no vault tunnel was ready and exited with error. The vault instances came up fine, it just needed a bit more time to try before it was ready. This increases the vault tunnel tries from an optimistic 1 sec * 60 to every 5 sec * 60
```release-note
NONE
```
> Increase time to try and get vault tunnel connection

- puppet/modules/prometheus/README.md
- puppet/modules/prometheus/manifests/node_exporter.pp
- puppet/modules/prometheus/spec/defines/rule_spec.rb
• Bump node-exporter to 0.16.0
• Migrate rules to 0.16.0 format
**Which issue this PR fixes**:
Most of our infra now exports series with `0.16.0`, we could get rid of `0.15.2` duplication rules altogether if we bump tarmak's node-exporter as well.
**Release note:**
```release-note
Bump node-exporter to 0.16.0 and update rules (breaking changes in metric names https://github.com/prometheus/node_exporter/releases/tag/v0.16.0)
```
> Bump node-exporter to 0.16.0 and update rules

- puppet/modules/prometheus/manifests/node_exporter.pp
/kind bug
```release-note
NONE
```
This corrects the relationships in for etcd's node_exporter to roll it out properly
> Make sure node_exporter are restarted correctly

- CHANGELOG.md
- puppet/modules/consul/manifests/config.pp
- puppet/modules/consul/manifests/init.pp
- puppet/modules/consul/manifests/params.pp
- puppet/modules/consul/manifests/service.pp
- puppet/modules/consul/spec/acceptance/single_node_spec.rb
- puppet/modules/consul/spec/acceptance/three_nodes_spec.rb
- puppet/modules/consul/spec/classes/config_spec.rb
- puppet/modules/consul/spec/classes/install_spec.rb
- puppet/modules/consul/spec/classes/service_spec.rb
- puppet/modules/consul/templates/consul.service.erb
- terraform/amazon/modules/vault/templates/vault_user_data.yaml
- terraform/amazon/templates/inputs.tf.template
This addresses a couple of consul improvement
* Updating consul to v1.2.3 (puppet module and terraform)
* Consul puppet acceptance health checks (puppet)
* Use `Type=notify` to wait for a ready consul to progress (puppet/terraform)
* Leave the cluster on terminate (puppet/terraform)
* Configure the correct agent token (terraform)
```release-note
Update consul to v1.2.3
Fixes: Consul nodes leave the cluster on terminate
Fixes: Consul agent status now having a proper token
```
> Improve consul and update

- pkg/tarmak/terraform.go
- pkg/terraform/templating.go
- pkg/terraform/terraform.go
Adds extra context to the error when the remote state is destroyed. This also enabled us to check for further errors in the future to give more context/advise
fixes #528 
```release-note
Provide advise when remote state has been destroyed
```
> Improve error when remote state is destroyed

- cmd/tarmak/cmd/cluster_force-unlock.go
- pkg/tarmak/interfaces/interfaces.go
- pkg/tarmak/tarmak.go
- pkg/tarmak/utils/context.go
- pkg/terraform/templating.go
- pkg/terraform/terraform.go
There is a maximum limit to the path name of sockets. This caused problems with config files in deep file paths. This moves the socket to /tmp so is never too long. This also ensures that all resources created in /tmp are now deleted at the end of run.
fixes #586 
```release-note
Move tarmak terraform provider socket to /tmp
```
/assign @MattiasGees 
/cc @MattiasGees @simonswine
> Move tarmak sock to /tmp and ensure cleanup

- pkg/apis/cluster/v1alpha1/cluster.go
- pkg/apis/cluster/v1alpha1/defaults.go
- pkg/tarmak/cluster/cluster.go
- terraform/amazon/modules/bastion/bastion.tf
- terraform/amazon/modules/bastion/bastion_iam.tf
- terraform/amazon/modules/bastion/inputs.tf
- terraform/amazon/modules/bastion/templates/role.json
- terraform/amazon/modules/vault/inputs.tf
- terraform/amazon/modules/vault/vault_iam.tf
- terraform/amazon/templates/inputs.tf.template
- terraform/amazon/templates/modules.tf.template
Additional IAM policies from the tarmak config were not enabled for vault and bastion instance pools. This PR creates a instance profile to the bastion instance to attach policies to. 
Bastion and vault instance pools now attach policies from arns in the config
fixes #519 
```release-note
Bastion and Vault instance pools now support additional policies declared in the config
```
/assign @simonswine @dippynark
> Enables additional policies for bastion and vault instance pools

- pkg/tarmak/environment/bastion.go
- pkg/tarmak/vault/vault.go
Adds both #512 #536 to ensure that tarmak selects a vault tunnel that is ready, not just the first.
```release-note
Select a healthy vault tunnel instead of always vault-1
```
> Automated cherry pick of #512 #536 origin release 0.4

- terraform/amazon/modules/vault/templates/vault_user_data.yaml
If for whatever reason consul exited, the systemd unit would not attempt to restart it. 
This PR adds a 10 second cool off before restarting, in-line with our upstream.
```release-note
Adds restart on failure to the consul service
```
> Adds restart on failure to consul service

- cmd/tarmak/cmd/root.go
Introduced with the addition of aliases in 4dcadfcc6.
```release-note
NONE
```
/kind bug
/assign @JoshVanL
> Fix escaping issue for kubectl and ssh arguments

- cmd/tarmak/cmd/cluster.go
- docs/generated/cmd/tarmak/tarmak_clusters_apply.rst
- docs/generated/reference/output/api-docs.html
- pkg/apis/tarmak/v1alpha1/types.go
- pkg/tarmak/cmd.go
- pkg/tarmak/interfaces/interfaces.go
- pkg/tarmak/tarmak.go
- pkg/terraform/terraform.go
auto-approve will auto approve all query responses to a cluster apply
auto-approve-deleting-data will auto approve all query responses about
data deletion to a cluster apply
fixes #549 
```release-note
Adds flags --auto-approve and --auto-approve-deleting-data to `cluster apply`
```
/hold
/assign
> Adds auto-approve and auto-approve-deleting-data flags to cluster apply

- pkg/tarmak/environment/environment.go
- pkg/tarmak/interfaces/interfaces.go
- pkg/tarmak/ssh.go
- pkg/tarmak/ssh/ssh.go
- pkg/tarmak/tarmak.go
fixes #567 
SSH key is able to hold 0400 or 0600 permissions. If it doesn't match tarmak will attempt to set to 0600.
SSH key file will be tested if it can be correctly parsed.
```release-note
NONE
```
> Ensure ssh key file holds correct permissions and can be parsed

- pkg/tarmak/interfaces/interfaces.go
- pkg/tarmak/provider/amazon/hosts.go
- pkg/tarmak/ssh/ssh.go
- pkg/tarmak/tarmak.go
Cleans up ssh run time assets, specifically control paths in /tmp/.
Fixes #592 
```release-note
Clean up ssh run time assets
```
/assign @MattiasGees
> Clean up ssh run time assets

- docs/generated/reference/output/api-docs.html
- docs/spelling_wordlist.txt
- docs/user-guide.rst
- pkg/apis/cluster/v1alpha1/cluster.go
- pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
- pkg/puppet/puppet.go
- pkg/tarmak/cluster/cluster.go
- puppet/modules/kubernetes/manifests/apiserver.pp
- puppet/modules/kubernetes/manifests/init.pp
- puppet/modules/kubernetes/spec/classes/apiserver_spec.rb
- puppet/modules/kubernetes/templates/kube-apiserver.service.erb
Unset depreciated flags for Kubernetes 1.11
fixes #425 
fixes #426 
```release-note
Unset API Server depreciated flags for Kubernetes version >= 1.11
```
> Unset deprecated flags from 1.11

- pkg/tarmak/provider/amazon/amazon.go
- pkg/tarmak/utils/consts/consts.go
Adds a back-off to AWS Describe Reserved Instance Offerings call in cases of rate limiting. If the error is anything else then we exit right away.
```release-note
NONE
```
> Adds backoff to describe reserved instance offerings

- pkg/tarmak/utils/context.go
Make utils/context.go use lowercase and consistent log output with the rest of tarmak
```release-note
NONE
```
> Use consistent log output

- pkg/tarmak/provider/amazon/amazon.go
- pkg/tarmak/tarmak.go
Fixes
1. `tarmak init` panics when run against empty ~/.tarmak
2. when a multicluster environment is initialised, the Tarmak CLI points at cluster instead of hub even though user will *have* to switch context to hub. This PR ensures that the default is for the CLI to point to the hub.
**Which issue this PR fixes** fixes #556 
```release-note
If the multicluster environment being initialised is the only existing environment, Tarmak CLI now points to that environment's 'hub' cluster
```
> Use hub in after inits of multi cluster environments

- pkg/tarmak/provider/amazon/amazon.go
Signed-off-by: Aled James <aledjms@gmail.com>
`tarmak init` panics when ~/.tarmak directory is empty
This PR wraps the invocation of the panicking function in a check for `nil`
```release-note
NONE
```
> Fix bug when running tarmak init with empty .tarmak directory

- cmd/tarmak/cmd/cluster.go
- docs/generated/cmd/tarmak/tarmak_clusters_apply.rst
- docs/generated/reference/output/api-docs.html
- pkg/apis/tarmak/v1alpha1/types.go
- pkg/tarmak/cmd.go
- pkg/terraform/terraform.go
Don't wait for wing to converge when we're not in infrastructure only
fixes #475
```release-note
Don't wait for wing conversion when we're not in infrastructure only
```
> Only converge on wing when not in infrastructure only

- puppet/modules/kubernetes/manifests/kubelet.pp
- puppet/modules/kubernetes/manifests/proxy.pp
- puppet/modules/kubernetes/spec/classes/kubelet_spec.rb
- puppet/modules/kubernetes/spec/classes/proxy_spec.rb
- puppet/modules/kubernetes/templates/kube-proxy-config.yaml.erb
- puppet/modules/kubernetes/templates/kube-proxy.service.erb
- puppet/modules/kubernetes/templates/kubelet-config.yaml.erb
- puppet/modules/kubernetes/templates/kubelet.service.erb
Adds support for kubelet and kube-proxy config files for Kubernetes clusters >= 1.11
fixes #424 
fixes #423 
```release-note
Adds configuration file for Kubelet and Kube-Proxy for Kubrnetes clusters >= 1.11 
```
> Kublet and Kube-Proxy config file

- cmd/tarmak/cmd/cluster.go
- docs/generated/cmd/tarmak/tarmak_clusters_apply.rst
- pkg/terraform/terraform.go
This also fixes the condition under which the auto-approve happens.
Fixes #636
```release-note
NONE
```
> Do not auto-approve state deletes by default

- puppet/modules/kubernetes/manifests/apiserver.pp
- puppet/modules/kubernetes/manifests/init.pp
- puppet/modules/kubernetes/manifests/kubelet.pp
- puppet/modules/kubernetes/spec/classes/apiserver_spec.rb
- puppet/modules/kubernetes/templates/kube-apiserver.service.erb
- puppet/modules/kubernetes/templates/kube-controller-manager.service.erb
- puppet/modules/kubernetes/templates/kube-scheduler.service.erb
- puppet/modules/kubernetes/templates/kubelet-config.yaml.erb
- puppet/modules/kubernetes/templates/kubelet.service.erb
```release-note
Disable profiling endpoints for control plane components
Enable service account lookup in etcd
Disable kubelets read-only ports
Hardening TLS configuration for Kubernetes >= 1.10
Do not repair malformed updates in apiserver
Fix insecure API server port enabled in >= 1.11
```
> Kube bench proposed security fixes

- pkg/tarmak/ssh/ssh.go
- pkg/tarmak/tarmak.go
When you init from a clean tarmak we would panic when trying to validate ssh through a nil pointer. We add a check here to make sure we actually have an environment to validate ssh against.
Also when we init a cluster we weren't setting it to the current cluster which meant operations such as `tarmak cluste list` would fail - bad first UX. When you now init a new cluster this will set it as current which makes sense to me.
fixes #640
```release-note
NONE
```
> Fix panic when initing environment  and validating ssh

- pkg/terraform/providers/tarmak/resource_vault_cluster.go
- pkg/terraform/providers/tarmak/resource_vault_instance_role.go
- pkg/terraform/providers/tarmak/rpc/bastion_instance_status.go
- pkg/terraform/providers/tarmak/rpc/rpc.go
- pkg/terraform/providers/tarmak/rpc/vault_cluster_status.go
- pkg/terraform/providers/tarmak/rpc/vault_instance_role.go
```release-note
Use vault-helper dry run ensure
```
/assign
/hold
> Use vault-helper dry run ensure

- cmd/tarmak/cmd/cluster_instances_ssh.go
- cmd/tarmak/cmd/cluster_kubectl.go
- cmd/tarmak/cmd/cluster_ssh.go
- cmd/tarmak/cmd/root.go
- cmd/tarmak/cmd/tarmak_test.go
- docs/generated/cmd/tarmak/tarmak_clusters_instances_ssh.rst
- docs/generated/cmd/tarmak/tarmak_clusters_ssh.rst
- docs/generated/cmd/tarmak/tarmak_kubectl.rst
- pkg/tarmak/utils/slices.go
This fixes a problem whereby we were not passing flags or `--` to kubectl correctly as they were being interpreted by croba, e.g. `tarmak kubectl exec -it shell-demo -- /bin/bash`
This sets all arguments after `kubectl` to be passed to `kubectl`.
fixes #477 
```release-note
Disable cobra interpreting flags after kubectl sub-command
```
> Disable cobra flags after kubectl sub-command

- packer/amazon/centos-puppet-agent-latest-kernel.json
- packer/amazon/centos-puppet-agent.json
The code tests if help of awscli is accessible and if that fails it removes the package awscli and installs it via pip.
```release-note
Fix centos 7.6 aws cli, download it through pip if it's not working
```
> Fix centos aws cli again

- packer/amazon/centos-puppet-agent-latest-kernel.json
- packer/amazon/centos-puppet-agent.json
- packer/amazon/cleanup.sh
- packer/amazon/configure_for_tarmak.sh
- packer/amazon/configure_latest_kernel.sh
This will hardcode the minor release of centos, due to continued instabilities right after the release of a new minor version
```release-note
Hardcode centos image release to 7.5.1804
```
> Hardcode centos release

- pkg/tarmak/kubectl/kubectl.go
When running tarmak kubeconfig/kubectl with a public ELB in front of apiserver, it gives errors. This comes down to not setting the certificate. This fixes that.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #659 
```release-note
Fix bug with kubectl/kubeconfig and public apiserver
```
> Fix error when running kube commands with public API

- hack/update-reference-docs.sh
- packer/amazon/configure_latest_kernel.sh
- pkg/tarmak/kubectl/kubectl.go
Cherry pick of #660 #658 on release-0.5.
#660: Fix error when running kube commands with public API
#658: Fix latest kernel packer image
```release-note
Fix bug with kubectl/kubeconfig and public apiserver
```
> Automated cherry pick of #660 #658

- docs/proposals/ssh-known_hosts.rst
- docs/spelling_wordlist.txt
As we are replacing the ssh command line tool for all programmatic use cases in favor of an in package solution, we have discovered some problems managing the ssh_known_hosts file correctly. This proposal aims to address these. 
```release-note
Management of SSH known_hosts file Proposal
```
> Adds management of ssh_known_hosts file proposal

- pkg/tarmak/cluster/cluster.go
- pkg/terraform/templating.go
- terraform/amazon/modules/bastion/bastion.tf
- terraform/amazon/modules/bastion/bastion_iam.tf
- terraform/amazon/modules/bastion/inputs.tf
- terraform/amazon/modules/bastion/outputs.tf
- terraform/amazon/modules/bastion/templates/wing_binary_read.json
- terraform/amazon/modules/jenkins/inputs.tf
- terraform/amazon/modules/kubernetes/iam_policies.tf
- terraform/amazon/modules/kubernetes/inputs.tf
- terraform/amazon/modules/kubernetes/templates/iam_tarmak_bucket_read.json
- terraform/amazon/modules/vault/inputs.tf
- terraform/amazon/modules/vault/templates/iam_tarmak_bucket_read.json
- terraform/amazon/modules/vault/vault_iam.tf
- terraform/amazon/templates/bastion_user_data.yaml.template
- terraform/amazon/templates/instance_pools/instance_pool_iam.tf.template
- terraform/amazon/templates/instance_pools/instance_pool_instance.tf.template
- terraform/amazon/templates/modules.tf.template
- terraform/amazon/templates/outputs.tf.template
- terraform/amazon/templates/wing_s3.tf.template
```release-note
Enable `--wing-dev-mode` on bastion instances for Wing development
```
/assign
> Enables wing-dev-mode on bastion instances

- puppet/hieradata/role/vault.yaml
- puppet/modules/consul/manifests/service.pp
- puppet/modules/tarmak/manifests/vault.pp
- puppet/modules/tarmak/spec/classes/vault_spec.rb
- puppet/modules/tarmak/spec/spec_helper.rb
- puppet/modules/vault_server/manifests/init.pp
- terraform/amazon/modules/vault/templates/vault_role_policy.json
Fixes the puppet to actually invoke the volume attachment for vault instances and assigns DescribeVolumes policy
```release-note
NONE
```
fixes #697
> Ensure volumes are correctly mounted for vault instances

- docs/existing-vpc.rst
- terraform/amazon/modules/network-existing-vpc/route53.tf
- terraform/amazon/modules/network-existing-vpc/vpc_endpoints.tf
fixes #706 
This removes this VPC endpoint from being created, along with a warning in the docs that it is strongly recommended that one exists. 
```release-note
S3 VPC endpoint is no longer created in deployments into an existing VPC
```
> Remove VPC endpoints from being created in existing VPC

- pkg/tarmak/ssh/ssh.go
If the bastion client connection has failed we should forget it to prevent keep trying it and warning.
```release-note
NONE
```
> Stop warning about failed bastion conn and forget

- puppet/modules/kubernetes_addons/templates/heapster-deployment.yaml.erb
This was race conditions since the introduction of kube-addon-manager
```release-notes
NONE
```
> Fix heapster vertical pod autoscaler race condition

- pkg/tarmak/ssh/ssh.go
fixes #717 
```release-note
Fall back to using instance tags if keys mismatch 
```
> If we mismatch keys, attempt to use the tags instead

- pkg/tarmak/provider/amazon/amazon.go
- pkg/tarmak/provider/amazon/amazon_test.go
This fixes a bug where we give an error with Tarmak that an instance is not available while it is.
Becuase AWS doesn't provide an API endpoint to check instance availability, we have to use a hacky way to get it. That is why we use the reserved instance offering API.
Tarmak used to check every AZ, but this is not needed for the on-demand instances and region is enough. Now we only check if we get items back from AWS and continue.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #642
This is also what Kops does, they only check for the whole region, not the individual AZs
```release-note …
```
> Fix bug where we give false errors on instance availability

- pkg/tarmak/cluster/cluster.go
- pkg/tarmak/instance_pool/instance_pool.go
- pkg/tarmak/interfaces/interfaces.go
- terraform/amazon/templates/instance_pools/instance_pool_variables.tf.template
Non-kubernetes instance did not receive those parameters correctly. This
PR makes sure they are set correctly in the terraform vars file.
```release-note
Fixes additional IAM policies correctly for non kubernetes roles
```
> Set additional IAM policies correctly for all roles

- docs/spelling_wordlist.txt
- docs/user-guide.rst
- docs/user-guide/aws-elasticsearch/settings.json
This will raise the number of fields allowed in JSON document.
```release-note
NONE
```
/assign @JoshVanL
> Improve documentation on Elasticsearch index config

- pkg/tarmak/ssh/ssh.go
Query input was failing, for example when asking whether to delete ebs volumes.
This only happened during or after terraform was run.
Stdin was unresponsive and always failed.
This was due to defaulting to os.Stdin for SSH execute sessions.
```release-note
NONE
```
fixes #729
> Don't default to os.Stdin for stdin in SSH execute sessions

- pkg/tarmak/kubectl/kubectl.go
SSH tunnel will now also attempt to use the server address in the kubeconfig. If it fails it wll create a new tunnel.
fixes #728 
```release-note
Re-use existing SSH tunnels to Kubernetes API server if they exist.
```
> Re-use working tunnel for kubectl

- cmd/tarmak/cmd/tunnel.go
- pkg/tarmak/interfaces/interfaces.go
- pkg/tarmak/kubectl/kubectl.go
- pkg/tarmak/ssh/tunnel.go
- pkg/tarmak/vault/tunnel.go
- pkg/tarmak/vault/tunnel_test.go
/assign
SSH tunnel have a timeout of 10 mins. Any new connections will disable this timer. Once that connection is closed the timeout is reset to 10 mins unless there is another open connection.
ixes #723 
```release-note
SSH tunnels timeout after 10 minutes of inactivity.
```
> Have timeout for tunnel, new connections reset timer

- pkg/apis/cluster/v1alpha1/constants.go
- pkg/apis/cluster/v1alpha1/defaults.go
- pkg/packer/packer.go
- pkg/tarmak/interfaces/interfaces.go
- pkg/tarmak/provider/amazon/image.go
- pkg/tarmak/tarmak_test.go
- pkg/version/version.go
- pkg/version/version_test.go
If EBS is encrypted and no images have been privately built then fallback to using Jetstack's publicly built image for that version. 
fixes #415 
```release-note
Fallback to using Jetstack's pre-built public AMI if none are privately built.
```
> Fallback to pre-built AMI images if none privately built

- .gitlab-ci.yml
- Makefile
- packer/amazon/configure_for_tarmak.sh
- pkg/packer/image.go
- pkg/tarmak/provider/amazon/tf_remote_state.go
Cherry pick of #680 #726 on release-0.5.
#680: Upgrade to go version 1.11.4
#726: Upgrade to Centos 7.6.1810
```release-note
Upgrade to Centos 7.6.1810
```
> Automated cherry pick of #680 #726

- puppet/modules/aws_es_proxy/manifests/instance.pp
- puppet/modules/aws_es_proxy/templates/aws-es-proxy.service.erb
- puppet/modules/fluent_bit/Gemfile.lock
- puppet/modules/fluent_bit/manifests/output.pp
- puppet/modules/fluent_bit/spec/acceptance/fluentbit_spec.rb
- puppet/modules/fluent_bit/spec/defines/output_spec.rb
- puppet/modules/fluent_bit/spec/fixtures/elasticsearch.repo
/assign
fixes #238 
```release-note
Adds fluent-bit acceptance tests
```
> Fluentbit beaker tests

- puppet/modules/prometheus/templates/kube-state-metrics-deployment.yaml.erb
Signed-off-by: Mattias Gees <mattias.gees@gmail.com>
Fix for errors in logs
```
E0221 10:13:53.230160       1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/collectors.go:91: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:monitoring:kube-state-metrics" cannot list resource "configmaps" in API group "" at the cluster scope
E0221 10:13:54.238317       1 reflector.go:205] k8s.io/kube-state-metrics/pkg/collectors/collectors.go:91: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:monitoring:kube-state-metrics" cannot list resource "secrets" in API group "" at the cluster scope
E0221 10:13:54.239928       1 reflector.go:205] …
```
> Update clusterrole for kube-state-metrics

- puppet/modules/kubernetes/manifests/init.pp
- puppet/modules/kubernetes/manifests/install.pp
- puppet/modules/kubernetes/manifests/kubelet.pp
- puppet/modules/kubernetes/manifests/params.pp
- puppet/modules/kubernetes/templates/fs.conf.erb
Increase inotify watch limits to Kubernetes instances.
max_user_instances = 8192,
max_user_watches = 524288,
```release-note
Increase inotify watch limits on Kubelet instances
```
> Increases inotify limits on Kubernetes instances

- Makefile
This reverts commit 01d018860da337e730e9ca4b0defc9b9f3ee5498.
```release-note
Down grade upx to 3.94 to build working Darwin binaries during releases
```
> Revert "Upgrade UPX to 3.95"

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/hashicorp/terraform/terraform/eval_diff.go
**What this PR does / why we need it**
Terraform has a bug where changes aren't processed when `ignore_changes` is active for other attributes. The PR https://github.com/hashicorp/terraform/pull/17856 fixes this but isn't merged. I created a fork of Terraform 0.11.11 and merged in that fix.
```release-note
Fix bug with Terraform that causes problems on Tarmak upgrades.
```
> Fix Terraform bug

- terraform/amazon/modules/network-existing-vpc/outputs.tf
```release-note
Fixes route 53 domain name reporting while using network-existing-vpc
```
> Backport fixes from network into network-existing-vpc

- terraform/amazon/modules/network-existing-vpc/outputs.tf
Cherry pick of #775 on release-0.6.
#775: Backport fixes from network into network-existing-vpc
> Automated cherry pick of #775

- pkg/tarmak/cluster/cluster.go
- pkg/tarmak/ssh/ssh.go
- pkg/tarmak/tarmak.go
This ensures the create ssh known hosts path shares the same directory as the ssh_config.
This stop an error occurring where a  known_hosts_path was being written to a directory that did not yet exist.
fixes #772 
```release-note
Ensure ssh_known_host file shares the same ssh_config directory.
```
> Ensure known hosts path is the same as ssh_config

- CHANGELOG.md
- pkg/apis/cluster/v1alpha1/defaults.go
- puppet/modules/tarmak/Makefile
Cherry pick of #786 on release-0.6.
#786: Upgrade default Kubernetes version to 1.12.6
> Automated cherry pick of #786

- puppet/modules/kubernetes_addons/templates/metrics-server-rbac.yaml.erb
- puppet/modules/kubernetes_addons/templates/metrics-server.yaml.erb
Signed-off-by: JoshVanL <vleeuwenjoshua@gmail.com>
Adds update permissions to metrics-server-nanny so that it is able to change the metrics-server deployment.
```release-note
Adds deployment update permissions to metrics-server-nanny container
```
> Adds update deploy permissions for metrics-server-nanny

- puppet/modules/kubernetes/manifests/apiserver.pp
- puppet/modules/kubernetes/spec/classes/apiserver_spec.rb
As per it's removal https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md
```release-note
Remove Initializers apiserver admission plugin for versions >= 1.14 
```
> Remove initializers apiserver admission plugin > 1.14

- puppet/modules/kubernetes_addons/templates/metrics-server-rbac.yaml.erb
- puppet/modules/kubernetes_addons/templates/metrics-server.yaml.erb
```release-note
Enable nanny container on metrics server but prevent clashing with kube-addon-manager
```
> Automated cherry pick of #791 origin release 0.6

- pkg/tarmak/provider/amazon/route53.go
It fixes a typo in the code when an error condition becomes true
```release-note
NONE
```
> fix typo in route53 file for dnsNameservers-zoneNameservers mismatch

- puppet/modules/consul/files/consul-backup.sh
- puppet/modules/consul/manifests/init.pp
- puppet/modules/consul/manifests/install.pp
- puppet/modules/consul/manifests/params.pp
- puppet/modules/consul/spec/classes/install_spec.rb
fixes #798 
```release-note
Fix consul-backinator installation
```
> Fixes the installation of consul-backinator

- puppet/modules/consul/Makefile
Cherry pick of #807 on release-0.6.
#807: Adds acceptance-single-node to consul puppet
> Automated cherry pick of #807

- puppet/modules/kubernetes/manifests/apiserver.pp
- puppet/modules/kubernetes/spec/classes/apiserver_spec.rb
- puppet/modules/kubernetes/templates/kube-apiserver.service.erb
- puppet/modules/tarmak/manifests/master.pp
We use `--service-account-api-audiences` for 1.12.x and `--api-audiences` for 1.13.
```release-note
Enables bound service account tokens for Kubernetes 1.12+
```
> Enable support for bound service account tokens fix

- docs/examples/aws-iam-authenticator.rst
- docs/generated/reference/output/api-docs.html
- docs/spelling_wordlist.txt
- docs/user-guide.rst
- docs/vault-setup-config.rst
- pkg/apis/cluster/v1alpha1/cluster.go
- pkg/puppet/puppet.go
- puppet/modules/kubernetes/manifests/apiserver.pp
- puppet/modules/kubernetes/manifests/aws_iam_authenticator_init.pp
- puppet/modules/kubernetes/manifests/init.pp
- puppet/modules/kubernetes/manifests/params.pp
- puppet/modules/kubernetes/spec/classes/apiserver_spec.rb
- puppet/modules/kubernetes/spec/classes/aws_iam_authenticator_init_spec.rb
- puppet/modules/kubernetes/templates/aws-iam-authenticator-init.service.erb
- puppet/modules/kubernetes/templates/kube-apiserver.service.erb
Signed-off-by: Sean Turner <sean@secops.ltd>
**Creates a systemd unit for pre-creating the iam-authenticator configuration, applies this if configured to do so, and sets it to occur before the apiserver starts**:
```release-note
Adds puppet classes, tests, tarmak configuration options, and some documentation for initialising the AWS IAM Authenticator (via systemd) for use with the Kubernetes apiserver(s) - note this doesn't install aws-iam-authenticator to the resulting cluster.
```
> Adds aws-iam-authenticator initialisation and instructions
